### PR TITLE
RPD ui refactor

### LINKED ISSUE #90992: Cyborg RPD UI Bluescreens (TypeError: Array(...).keys(...).map is not a function)
### Client Version:

_No response_

### Issue Summary:

Image

### Round ID:

_No response_

### Test Merge Information:

_No response_

### Reproduction Steps:

Image

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Fixes a possible bluescreen in the RPD. Issue was caused when the backend didn't send the static data that the UI relied upon to populate pipe layers (perhaps due to throttling)

Reworks the UI a bit so that the content section is scrollable instead of the entire window. This prevents the top content from disappearing if you're scrolling available pipes. Adds some extra typing where it was type: any

image

## Why It's Good For The Game
Fixes #90992
## Changelog
:cl:
fix: Fixed an uncommon bluescreen in the rapid pipe dispenser UI.
/:cl:

### CODE REVIEW

File: tgui/packages/tgui/interfaces/RapidPipeDispenser.tsx [hunk 1]
```diff
@@ -231,13 +219,21 @@ const LayerSelect = (props) => {
...
-const PreviewSelect = (props) => {
+function PreviewSelect(props: PreviewSelectProps) {
   const { act } = useBackend<Data>();
+  const { previews, pipe_type, category } = props;
+
   return (
     <Box>
-      {props.previews.map((preview) => (
+      {previews.map((preview) => (
         <Button
```
Comment (AyIong) [inline tgui/packages/tgui/interfaces/RapidPipeDispenser.tsx:237]: You can try ImageButton

Comment (jlsnow301) [reply tgui/packages/tgui/interfaces/RapidPipeDispenser.tsx]: image

File: tgui/packages/tgui/interfaces/RapidPipeDispenser.tsx [hunk 2]
```diff
@@ -231,60 +219,66 @@ const LayerSelect = (props) => {
...
-              'pipes32x32',
-              preview.dir + '-' + preview.icon_state,
-            ])}
-            style={{
-              transform: 'scale(1.5) translate(9.5%, 9.5%)',
+    <Stack fill>
+      {recipe.previews.map((preview) => (
+        <Stack.Item key={preview.dir}>
+          <ImageButton
+            asset={['pipes32x32', preview.dir + '-' + preview.icon_state]}
```
Comment (AyIong) [inline tgui/packages/tgui/interfaces/RapidPipeDispenser.tsx:238]:
```suggestion
            asset={['pipes32x32', `${preview.dir}-${preview.icon_state}`]}
```
I don't know how you feel about it, but I think it's better.

Comment (jlsnow301) [reply tgui/packages/tgui/interfaces/RapidPipeDispenser.tsx]: added
