### PR TITLE
Makes searchbars more responsive

### LINKED ISSUE #80679: protolathe searchbars are horrible to type in
Reporting client version: 515.1623

## Issue Summary

i dont even know what the fuck is wrong with them but typing in them is laggy as shit and it messes with your input

## Round ID:
[221386](https://scrubby.melonmesa.com/round/221386)

## Testmerges:
- [[TM ONLY] Remove 'natural' beheading](https://www.github.com/tgstation/tgstation/pull/80439)
- [Rewrites dropdown and popper components as FCs](https://www.github.com/tgstation/tgstation/pull/80556)

## Reproduction:

1. open protolathe
2. try to search a phrase like "autolathe"
3. struggle

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Identified in Issue #80679: The current implementation of the search bar component incorporates a timeout mechanism that's conflicting with the controlled input behavior. This is leading to a race condition where user input is inconsistently modified due to the timeout. To address this, I've eliminated the timer and applied a uniform debounce of 200ms to all onInput events. This approach aims to enhance input responsiveness and prevent the erratic behavior previously observed.

Basic code maintenance: The search bar component itself is in fabrication but used elsewhere, so I remade it as a functional component and placed it in /common instead.
 
<details>
<summary>video</summary>

mMiNInzCJp

</details>

## Why It's Good For The Game
Protolathes are bearable again
Fixes #80679

## Changelog

:cl:
fix: Protolathe input should feel more responsive.
/:cl:

### CODE REVIEW

**Comment by necromanceranne** [comment]
thank goodness, this was driving me crazy and I thought my keyboard was broken at first.

File: tgui/packages/tgui/components/TextArea.tsx [hunk 1]
```diff
@@ -117,8 +117,6 @@ export const TextArea = forwardRef(
       const input = textareaRef.current;
       if (!input) return;
 
-      input.value = toInputValue(value);
```
Comment (jlsnow301) [inline tgui/packages/tgui/components/TextArea.tsx:120]: not needed as this fires in the next useeffect
