### PR TITLE
request manager refactor

### LINKED ISSUE #84559: The "Type Filter" Button at Requests Manager doesn't work
Reporting client version: 515.1640

## Issue Summary
The "Type Filter" Button at the Requests Manager verb's panel does not work. You click it and nothing happens.

## Round ID:
[231459](https://scrubby.melonmesa.com/round/231459)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Allows for proxy atoms in object melee attack chain](https://www.github.com/tgstation/tgstation/pull/83860)
- [New Traitor mech: Justice.](https://www.github.com/tgstation/tgstation/pull/84097)
- [Flattens The Floor Plane](https://www.github.com/tgstation/tgstation/pull/84350)

### PR DESCRIPTION
**Pull request by Ben10Omintrix**
## About The Pull Request
refactors request manager into typescript and minor QOL and bug fixes along the way. the type filter wasnt working before. also there was a noticible long delay between clicking filter types and getting any feedback, which is now fixed. the button was floating outside its boarder so i shoved it back in. also u no longer need to keep pressing enter when ur searching for stuff through the input bar

## Why It's Good For The Game
closes #84559

## Changelog
:cl:
refactor: request managers have been refactored to typescript
fix: request manager type filter now works
/:cl:

### CODE REVIEW

**Comment by jlsnow301** [comment]
prettier issue, please fix the formatting here or lmk if you're having trouble with it

File: tgui/packages/tgui/interfaces/RequestManager.tsx [hunk 1]
```diff
@@ -3,37 +3,66 @@
...
-    const filterText = searchText.toLowerCase();
-    displayedRequests = displayedRequests.filter(
-      (request) =>
-        decodeHtmlEntities(request.message)
-          .toLowerCase()
-          .includes(filterText) ||
-        request.owner_name.toLowerCase().includes(filterText),
-    );
+  const search = createSearch(
+    searchText.toLowerCase(),
```
Comment (jlsnow301) [inline tgui/packages/tgui/interfaces/RequestManager.tsx:59]: toLowerCase() is implied with createSearch, same with the stringifier. should be equal without
```suggestion
    searchText,
```

**Comment by SomeRandomOwl** [comment]
Oh just realized someone beat me to this, i was going to do something similar because the request manager doesnt actually properly sort requests by timestamp
