### PR TITLE
fixes the chat audio player, typescripts it

### LINKED ISSUE #88968: 516 issue: stopping music player bluescreens the chat
### Client Version:

516.1649

### Issue Summary:

The TGUI chat bluescreens when you try to stop the music player
Running "fix chat" verb fixes it but i think the music still keeps playing

### Round ID:

maybe

### Test Merge Information:

nah

### Reproduction Steps:

1. Have an admin play music
2. Try to stop the music using the square button on the music player
3. Have your chat bluescreen with TGUI failing

### PR DESCRIPTION
**Pull request by hry-gh**
## About The Pull Request

516 broke the funny way we were playing audio before which was built for ie8 compatibility. this version works for both ie11 and wv2

## Why It's Good For The Game

for some reason we decided admins playing music was a good idea

## Changelog

:cl:
fix: the admin music player works again on 516
/:cl:

fixes https://github.com/tgstation/tgstation/issues/88968

from (https://github.com/cmss13-devs/cmss13/pull/8606, but i know the guy so it's fine)

### CODE REVIEW

**Review by Absolucy — APPROVED** [review]

File: tgui/packages/tgui-panel/audio/player.ts [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+
+    logger.log('stopping');
+
+    this.element.pause();
+    this.element = null;
+
+    this.onStopSubscribers.forEach((subscriber) => subscriber());
+  }
+
+  setVolume(volume: number): void {
```
Comment (jlsnow301) [inline tgui/packages/tgui-panel/audio/player.ts:86]: for consistency, the other methods should also mark their return type

**Review by jlsnow301 — COMMENTED** [review]
this pr seems to remove props from the audioplayer class (ex: volume). is this no longer needed?

**Comment by jlsnow301** [comment]
> i might be really stupid,

same, disregard
