### PR TITLE
Fix missing emergency shuttle prices

### LINKED ISSUE #94646: Emergency shuttle purchase menu is missing shuttle prices
### Issue Summary:

The emergency shuttle purchase screen no longer displays the cost of each shuttle option:

Image

### Reproduction Steps:

Open the shuttle purchase menu on the comms console.

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

Fixes https://github.com/tgstation/tgstation/issues/94646 and shows the price of each emergency shuttle option.

image

## Why It's Good For The Game

Emergency shuttle price is no longer a mystery

## Changelog

:cl: LT3
fix: Emergency shuttle purchase menu now lists the shuttle prices
/:cl:

### CODE REVIEW

File: tgui/packages/tgui/interfaces/CommunicationsConsole/BuyingShuttle.tsx [hunk 1]
```diff
@@ -76,14 +76,14 @@ function ShuttleCard(props: ShuttleCardProps) {
...
-              ? `You need ${shuttle.creditCost - budget} more credits.`
+              ? `You need ${shuttle.creditCost - budget} more ${displayed_currency_full_name}.`
               : shuttle.emagOnly
                 ? EMAG_SHUTTLE_NOTICE
                 : undefined
           }
           tooltipPosition="left"
         >
-          {shuttle.emagOnly ? 'Buy' : 'Purchase'}
+          {shuttle.emagOnly ? 'Buy' : `${shuttle.creditCost} ${displayed_currency_name}`}
```
Comment (timothymtorres) [inline tgui/packages/tgui/interfaces/CommunicationsConsole/BuyingShuttle.tsx:86]: Are you able to include the coin icon, like the one next to the right of the `Back` button that is:

`<Icon name="coins" color="gold" />`
