### PR TITLE
Tram v6/Transport Subsystem

### LINKED ISSUE #76270: Tram indicator sign sometime uses wrong emissive overlay on tram power loss
## Round ID: [208898](https://scrubby.melonmesa.com/round/208898)

https://github.com/tgstation/tgstation/assets/83487515/ab97e790-e76e-4f62-b192-69de5b2ad726

Some signs were fine, others used the wrong emissive overlay. Hm.

## Reproduction:

Cut power to the tram in some particular way?

### LINKED ISSUE #78068: Tram controls don't make the tram actually move
## Round ID: [213868](https://scrubby.melonmesa.com/round/213868) and many before

When you try to move the tram with the tram controls (the ones on the tram), it says it'll go there. The doors close, then the doors just open again without it actually having moved. And the UI of those controls think you are in the location you wanted to go to now.

The tram call buttons outside the tram work though to call it to the current location.

## Testmerges:

https://github.com/tgstation/tgstation/pull/77307

## Reproduction:

1. Get on Tram
2. Try to operate the tram controls
3. Notice Tram doesn't move

### PR DESCRIPTION
**Pull request by lessthnthree**
## About The Pull Request

HackMD: https://hackmd.io/@lessthanthree/BJoiOEGP3

A year since the last tram update, this one focuses on:
- Cleaning up, documenting tram code and bringing it from tram process/industrial lift into its own Transport subsystem
- Improving tram resiliency, logging, and admin tools to see the tram's performance and deal with tram issues
- Add QOL like context, examine info, clear messages to make the tram less of a 'black box' for players to work with
- Simplify the building of tram components, allowing players to repair, customize, and rebuild when it breaks
- Turn Tram Malfunction event and Ninja drain into something the players can actually respond and fix 

## Why It's Good For The Game

It sucks when the tram breaks, particularly when you can't do anything about or know what happened. By giving players and admins the ability to build/spawn replacement parts and get the tram back up and running with less effort improves the round and hopefully we have less where the tram is outright broken all round.

Adding small, optional tasks similar to the Radiation Leak event give engineers a way to contribute to malfunction events to speed up getting things back to normal.

Fixes the sprite and layering issues with the various tram components, doors clipping through walls. Build more tram bars, security checkpoints, and other interesting things without having to build actual walls and sometimes wreck the tram.

tram_pr_1

tram_pr_2

https://github.com/tgstation/tgstation/assets/83487515/59d59d3d-fd16-4f92-951f-6fe4a06842de

Closes https://github.com/tgstation/tgstation/issues/78068
Closes https://github.com/tgstation/tgstation/issues/76270

## Changelog

:cl: LT3
refactor: Tram process/industrial lift refactored into transport subsystem
refactor: Nanotrasen has traded in last year's tram for a new 2563 model!
add: Tram spoilers can be emagged to cause extra damage on collision
add: Tram can now be manually driven from the controller cabinet using TGUI
add: Tram floor tiles can be created using plastic sheets
add: Tram walls/floor tiles can be removed, repaired, and replaced
add: Tram frames (girder) can be created/placed using titanium sheets
add: Broken tram machinery causes crossing signals to malfunction
add: Ninja drain on tram controls will cause minor malfunction on other tram components
add: Engineers can stop/start and disable the tram
qol: Tram machinery now has context hints and examine text to indicate status
qol: Tram remote no longer requires physically touching the tram before using
code: You can now construct furniture and other decorations on the tram
code: Tram electrocution is now a component, not a turf
code: Tram stats are now persistent between rounds and logged to feedback
code: Engineers can now end Tram Malfunction event early by repairing the tram controller
code: Replacement tram machinery is researchable and buildable
code: Most tram machinery now performs auto configuration instead of hardcoded map values
code: Tram remote can now set specific destinations
code: Tram actions/errors now create log entries
balance: Tram base floor is no longer indestructible
balance: Damaged energized tram plates have a chance to electrocute
fix: Tram destination signs should no longer display incorrect emissive overlays
fix: Tram crossing signals no longer turn amber before the tram starts moving
image: Improved sprites for most tram components
image: Removed all unused/duplicate tram icons from .dmis
image: Colors are now consistent between status, tram, incident displays
admin: Reset tram commands available to admins in the debug panel
/:cl:

### CODE REVIEW

**Comment by distributivgesetz** [comment]
the big one

**Comment by LemonInTheDark** [comment]
How many lines of this is code changes

**Comment by lessthnthree** [comment]
> How many lines of this is code changes

1-2000? Most is moving and variables. johnfulpwillard didn't take long to go through it

**Comment by Ghommie** [comment]
From the video, I can see a small regression on the glide size inheritance. Tthe objects being moved beside the transport modules are lagging behind as the tram moves. Hopefully it'll get fixed soon.

Otherwise, that's kickass.

**Comment by lessthnthree** [comment]
> From the video, I can see a small regression on the glide size inheritance. The objects being transported by the tram the transport modules objects are lagging behind as it moves. Hopefully it'll get fixed soon.
> 
> Otherwise, that's kickass.

Glide slide is usually pretty good. The video has an occurrence of https://github.com/tgstation/tgstation/issues/77722, which isn't fixed yet. There's some items on the lower z-level that it's pulling still registered to the tram.

**Comment by Googles-Hands** [comment]
The new menu is worse than the one we have currently, maybe that could be a sort of maintenance mode for something, but sacrificing the nice, current UI for that isn't good imo.

**Comment by lessthnthree** [comment]
Sorry if it wasn't clear, that is the maintenance menu. There's no change to the original tram controls mounted on the window.

File: tgui/packages/tgui/interfaces/CrossingSignal.tsx [hunk 1]
```diff
@@ -0,0 +1,52 @@
+import { useBackend } from '../backend';
+import { Section, LabeledList, Flex } from '../components';
+import { Window } from '../layouts';
+
+type TransportData = {
+  sensorStatus: boolean;
```
Comment (jlsnow301) [inline tgui/packages/tgui/interfaces/CrossingSignal.tsx:6]: We don't have these, pls import BooleanLike

File: tgui/packages/tgui/interfaces/CrossingSignal.tsx [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+export const CrossingSignal = (props, context) => {
+  const { act, data } = useBackend<TransportData>(context);
+
+  const { sensorStatus, operatingStatus, inboundPlatform, outboundPlatform } =
+    data;
+
+  return (
+    <Window title="Crossing Signal" width={400} height={175} theme="dark">
+      <Window.Content>
+        <Flex direction="row">
```
Comment (jlsnow301) [inline tgui/packages/tgui/interfaces/CrossingSignal.tsx:25]: You should be able to remove flex and flex item- these are only used if you're fitting multiple things on screen and need to organize them.

If you're adding more, this would also just need to be replaced with Stack (flex is deprecated)

File: tgui/packages/tgui/interfaces/TramController.tsx [hunk 3]
```diff
@@ -0,0 +1,279 @@
...
+  transportId: string;
+  controllerActive: number;
+  controllerOperational: BooleanLike;
+  travelDirection: number;
+  destinationPlatform: string;
+  idlePlatform: string;
+  recoveryMode: BooleanLike;
+  currentSpeed: number;
+  currentLoad: number;
+  statusSF: boolean;
```
Comment (jlsnow301) [inline tgui/packages/tgui/interfaces/TramController.tsx:17]: BooleanLike

File: tgui/packages/tgui/interfaces/TramController.tsx [hunk 4]
```diff
@@ -0,0 +1,279 @@
+import { useBackend, useLocalState } from '../backend';
+import { BooleanLike } from 'common/react';
+import { Section, NoticeBox, Dropdown, LabeledList, ProgressBar, Flex, Button } from '../components';
+import { toFixed } from 'common/math';
+import { Window } from '../layouts';
+
+type TransportData = {
```
Comment (jlsnow301) [inline tgui/packages/tgui/interfaces/TramController.tsx:7]: While I won't knock this behavior I think it's not necessary for a local type to name it so explicitly- just "data" is fine if it's the backend data

File: tgui/packages/tgui/interfaces/TramController.tsx [hunk 5]
```diff
@@ -0,0 +1,279 @@
...
+              </NoticeBox>
+              <Button
+                icon="square"
+                color="bad"
+                my={1}
+                lineHeight={2}
+                minWidth={7}
+                minHeight={2}
+                textAlign="center"
+                content="E-Stop"
```
Comment (jlsnow301) [inline tgui/packages/tgui/interfaces/TramController.tsx:147]: Please use these as the child rather than using content
`<Button>E-Stop</Button>`

File: tgui/packages/tgui/interfaces/TramController.tsx [hunk 6]
```diff
@@ -0,0 +1,279 @@
...
+  const [tripDestination, setTripDestination] = useLocalState(
+    context,
+    'TramDestination',
+    ''
+  );
+
+  return (
+    <Window title="Tram Controller" width={800} height={325} theme="dark">
+      <Window.Content>
+        <Flex direction="row">
```
Comment (jlsnow301) [inline tgui/packages/tgui/interfaces/TramController.tsx:65]: Medium sized ask- switch these to stack, stack item respectively. Instead of using pixel measurements for H/W dimensions, use grow property, ie,

```ts
// this would take 1/3 the space
<Stack.Item grow={1}
// this would take 2/3 the space
<Stack.Item grow={2}
```

**Review by jlsnow301 — CHANGES_REQUESTED** [review]

File: tgui/packages/tgui/interfaces/TramController.tsx (hunk 6 above)
Comment (lessthnthree) [reply tgui/packages/tgui/interfaces/TramController.tsx:65]: Sure

File: tgui/packages/tgui/interfaces/CrossingSignal.tsx (hunk 2 above)
Comment (lessthnthree) [reply tgui/packages/tgui/interfaces/CrossingSignal.tsx:25]: Thanks.

File: tgui/packages/tgui/interfaces/TramController.tsx (hunk 6 above)
Comment (lessthnthree) [reply tgui/packages/tgui/interfaces/TramController.tsx:65]: Sure.

File: tgui/packages/tgui/interfaces/TramController.tsx (hunk 5 above)
Comment (lessthnthree) [reply tgui/packages/tgui/interfaces/TramController.tsx:147]: Not quite sure why I did it like that anyways.

Comment (jlsnow301) [reply tgui/packages/tgui/interfaces/TramController.tsx:147]: suggestions, maybe! content was the old method. sometimes causes issues with spacing

**Comment by ju45he** [comment]
Now all we need is the ability to make smaller sized Trams from scratch, literally roller-coaster station 13, we can make THEME PARKS IN SPESS

File: code/controllers/subsystem/transport.dm [hunk 7]
```diff
@@ -0,0 +1,160 @@
+PROCESSING_SUBSYSTEM_DEF(transport)
+	name = "Transport"
+	wait = 0.5
```
Comment (ZephyrTFA) [inline code/controllers/subsystem/transport.dm:3]: 0.5 what? Use the correct interval define please

Comment (lessthnthree) [reply code/controllers/subsystem/transport.dm:3]: Ah yeah, I just copied the existing value. Fixed.

File: code/modules/transport/tram/tram_controls.dm [hunk 8]
```diff
@@ -0,0 +1,202 @@
...
+			var/obj/effect/landmark/transport/nav_beacon/tram/platform/destination_platform
+			for(var/obj/effect/landmark/transport/nav_beacon/tram/platform/destination as anything in SStransport.nav_beacons[specific_transport_id])
+				if(destination.platform_code == params["destination"])
+					destination_platform = destination
+					break
+
+			if(isnull(destination_platform))
+				return FALSE
+
+			SEND_SIGNAL(src, COMSIG_TRANSPORT_REQUEST, specific_transport_id, destination_platform.platform_code)
```
Comment (Kylerace) [inline code/modules/transport/tram/tram_controls.dm:114]: i dont understand why this is a signal instead of a proc call

**Review by Kylerace — CHANGES_REQUESTED** [review]

File: code/modules/transport/_transport_machinery.dm [hunk 9]
```diff
@@ -0,0 +1,194 @@
...
+		context[SCREENTIP_CONTEXT_LMB] = "repair frame"
+
+	return CONTEXTUAL_SCREENTIP_SET
+
+/**
+ * Finds the tram
+ *
+ * Locates tram parts in the lift global list after everything is done.
+ */
+/obj/machinery/transport/proc/link_tram()
```
[the remark this answers is not in the document]
Comment (lessthnthree) [reply code/modules/transport/_transport_machinery.dm:56]: yeah good idea

File: code/modules/transport/tram/tram_controls.dm (hunk 8 above)
Comment (lessthnthree) [reply code/modules/transport/tram/tram_controls.dm:114]: it can be, I was treating the controls the same as tram request buttons which also send signals

File: code/modules/antagonists/malf_ai/malf_ai_modules.dm [hunk 10]
```diff
@@ -1267,7 +1267,7 @@ GLOBAL_LIST_INIT(malf_modules, subtypesof(/datum/ai_module))
 		clicked_vendor.balloon_alert(ai_caller, "inoperable!")
 		return FALSE
 
-	var/picked_dir_string = show_radial_menu(ai_caller, clicked_vendor, GLOB.all_radial_directions, custom_check = CALLBACK(src, PROC_REF(radial_check), caller, clicked_vendor))
+	var/picked_dir_string = show_radial_menu(ai_caller, clicked_vendor, SStransport.all_radial_directions, custom_check = CALLBACK(src, PROC_REF(radial_check), caller, clicked_vendor))
```
[the remark this answers is not in the document]
Comment (lessthnthree) [reply code/modules/antagonists/malf_ai/malf_ai_modules.dm:1270]: oh. I moved all the global lists it was using. I thought this was specific to tram/elevators

File: code/modules/transport/transport_module.dm [hunk 11]
```diff
@@ -905,3 +925,13 @@ GLOBAL_LIST_INIT(all_radial_directions, list(
...
 	if(iterations)
 		addtimer(CALLBACK(src, PROC_REF(clear_turfs), turfs, iterations), 1)
+
+/obj/structure/transport/linear/tram/proc/estop_throw(throw_direction)
+	if(prob(50))
+		do_sparks(2, FALSE, src)
+	for(var/mob/living/passenger in transport_contents)
+		to_chat(passenger, span_userdanger("The tram comes to a sudden, grinding stop!"))
+		var/throw_target = get_edge_target_turf(src, throw_direction)
+		passenger.throw_at()
```
Comment (Kylerace) [inline code/modules/transport/transport_module.dm:935]:
```suggestion
```

Comment (lessthnthree) [reply code/modules/transport/transport_module.dm:935]: The whole throw part of it?

File: code/modules/transport/tram/tram_structures.dm [hunk 12]
```diff
@@ -0,0 +1,579 @@
...
+	var/tram_wall_type = /obj/structure/tram
+	var/girder_type = /obj/structure/girder/tram
+	var/mutable_appearance/damage_overlay
+	var/break_sound = SFX_SHATTER
+	var/knock_sound = 'sound/effects/glassknock.ogg'
+	var/bash_sound = 'sound/effects/glassbash.ogg'
+
+/obj/structure/tram/solid
+	desc = "A lightweight titanium composite structure with tinted titanium silicate panels."
+	opacity = TRUE
```
Comment (Kylerace) [inline code/modules/transport/tram/tram_structures.dm:55]: dont put this or anything that has opacity on the roundstart tram, it causes SSlighting to spam lighting updates every time the tram moves a tile.
Screenshot_3122

File: code/modules/transport/tram/tram_machinery.dm [hunk 13]
```diff
@@ -0,0 +1,106 @@
...
+		LAZYADD(available_platforms, platform.name)
+
+	var/selected_platform = tgui_input_list(user, "Set the platform ID", "Platform", available_platforms)
+	var/obj/effect/landmark/transport/nav_beacon/tram/platform/change_platform
+	for(var/obj/effect/landmark/transport/nav_beacon/tram/platform/destination as anything in SStransport.nav_beacons[specific_transport_id])
+		if(destination.name == selected_platform)
+			change_platform = destination
+			break
+
+	if(!change_platform || QDELETED(user) || QDELETED(src) || !usr.can_perform_action(src, FORBID_TELEKINESIS_REACH))
```
Comment (Kylerace) [inline code/modules/transport/tram/tram_machinery.dm:19]:
```suggestion
	if(!change_platform || QDELETED(user) || QDELETED(src) || !user.can_perform_action(src, FORBID_TELEKINESIS_REACH))
```

**Review by Kylerace — CHANGES_REQUESTED** [review]

File: code/modules/transport/tram/tram_structures.dm (hunk 12 above)
Comment (lessthnthree) [reply code/modules/transport/tram/tram_structures.dm:55]: ah, didn't know opacity did that. I'll go over it.
