### PR TITLE
Fixes techweb scrolling cutting off the last node

### LINKED ISSUE #90220: Last node in research UI is cut off
### Client Version:

_No response_

### Issue Summary:

Last node in research UIs is always cut off

image

### Round ID:

_No response_

### Test Merge Information:

_No response_

### Reproduction Steps:

Open R&D console

### PR DESCRIPTION
**Pull request by SmArtKar**
## About The Pull Request

Biome seems to have butchered the file, but I've just swapped the nodes into a scrollable section instead of relying on scrolling through 100%d flexes (where two top elements moved the techweb down)

Closes #90220

## Changelog
:cl:
fix: Fixed techweb scrolling cutting off the last node
/:cl:

### CODE REVIEW

**Comment by jlsnow301** [comment]
I don't think biome will work unless it's installed in the project. Prettier?

File: tgui/packages/tgui/interfaces/Techweb/Overview.tsx [hunk 1]
```diff
@@ -86,11 +86,13 @@ export function TechwebOverview(props) {
         </Flex>
       </Flex.Item>
       <Flex.Item className="Techweb__OverviewNodes" height="100%">
-        <VirtualList key={tabIndex + searchText}>
-          {displayedNodes.map((n) => (
-            <TechNode node={n} key={n.id} />
-          ))}
-        </VirtualList>
+        <Section fill scrollable height="100%">
+          <VirtualList key={tabIndex + searchText}>
```
Comment (jlsnow301) [inline tgui/packages/tgui/interfaces/Techweb/Overview.tsx:90]: 1. fill is height 100%
2. shouldn't need a key here
