### PR TITLE
RPG Loot: Revisited & READY

### LINKED ISSUE #53824: Alt-clicking a blood decal tile may display 150+ different blood icons at once
## Round ID:
[146560](https://scrubby.melonmesa.com/round/145348) Terry. 

## Testmerges:
#53596
#53329

## Reproduction:
Not sure how to reproduce, but this is what I did:

1. Surrounded a tile with ATMOS holofan projector fans. 
2. Used an RCD to remove the plating of the middle tile, making a hole to space. 
3. Constructed half tile rwindows to surround the hole. 
4. Alt-clicked one of the holofan tiles to be able to click the rwindow with screwdriver. It had a blood decal on it. 

Not sure if any of the above matters at all. 

**Result:** 

After that, alt-clicking any bloody tile on station (but not in the CTF arena) would make it look the same.

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Revival of #72881

A new alt click window with a tarkov-y loading spinner. Replaces the object item window in stat panel.

## Videos
<details>
<summary>vids</summary>

toggleable grouping:
syAA5zf6RK

now lists the floor as first obj:
abc

in action:
dreamseeker_IkrPKt2QZt

</details>

## features:
- search by name
- 515 image generator is much faster than alt click menu
- opening a gargantuan amount of items shouldnt freeze your screen
- groups similar items together in stacks by default, toggleable
- shows tile as first item
- <kbd>Shift</kbd> and <kbd>Ctrl</kbd> compatible with LMB :computer_mouse:
- RMB points points at items (sry i could not get MMB working)
- key <kbd>Esc</kbd> to exit the window.

For devs:
- A new image generation tech.
- An error refetch mechanic to the Image component
- It does not "smart track" the items being added to the pile, just reopen or refresh. This was a design decision.

## Why It's Good For The Game
Honestly I just dislike the stat panel

Fixes #53824

Fixes 
image

## Changelog
:cl:
add: Added a loot window for alt-clicking tiles.
del: Removed the item browser from the stat panel.
/:cl:

### CODE REVIEW

**Comment by atlasle** [comment]
this is neat but if it takes a full second to load what items are inside then its objectively worse than the atom menu

**Comment by jlsnow301** [comment]
> this is neat but if it takes a full second to load what items are inside then its objectively worse than the atom menu

i've changed it to more closely mimic the stat panel. it immediately loads all items in tile contents. images take those seconds to load, bit by bit. you can search for, hover over, and click on items from the very start even if there is no image loaded

**Comment by ZephyrTFA** [comment]
don't see the usefulness of making it load slowly

**Comment by Xackii** [comment]
What takes longer to load? Is the stat panel or tgui with loading animation

**Comment by Pickle-Coding** [comment]
> this is neat but if it takes a full second to load what items are inside then its objectively worse than the atom menu

Statpanel only updates once per 6 seconds, which is absolutely horrible when dealing with a lot of items.

**Comment by Pickle-Coding** [comment]
Also why does it only load up to 5 items at a time? Why not just do a tick check?

**Comment by jlsnow301** [comment]
> don't see the usefulness of making it load slowly

I thought it was an aesthetic way of preventing it from eating the server

> Also why does it only load up to 5 items at a time? Why not just do a tick check?

But if you two don't like it and just want it to run at capacity I guess that works too

**Comment by CRITAWAKETS** [comment]
This should also include the turf, since the biggest use for alt clicking tends to be engineers using it to precisely target turfs in places where something's obscured by objects (mostly for piping).

**Comment by jlsnow301** [comment]
> This should also include the turf

updated

**Review by ZephyrTFA — APPROVED** [review]

**Comment by breadcrombs** [comment]
escape from terry

**Comment by Crushtoe** [comment]
Bug came up in play, it seems alt-click interactions with things on tiles is bringing up this menu when it shouldn't --- rotating a chair, for instance, uses alt-click as a shortcut, and with this PR shoves a popup menu in your face. Probably also applies to any other structure interaction, or maybe just chairs.

**Comment by jlsnow301** [comment]
> Bug came up in play, it seems alt-click interactions with things on tiles is bringing up this menu when it shouldn't --- rotating a chair, for instance, uses alt-click as a shortcut, and with this PR shoves a popup menu in your face. Probably also applies to any other structure interaction, or maybe just chairs.

will take a look at this, i think i noticed it as well. should be a simple fix

**Comment by Crushtoe** [comment]
Is there any chance this could get a toggle? I personally prefer the stat panel; it takes up space in the UI, it should do something, and as-is it gives you a list of tiles. The new pop-up menu looks aesthetic, but it takes up space in the main game panel where I want to see things, and it makes the stat panel a dead use of space. I dunno how much the maintainers like or dislike preferences, or you care to add a pref, but I'd appreciate it being toggleable.

**Comment by DustyExaliber** [comment]
I am going to agree with Crushtoe here it looks nice but it feels unironically sort-of clunkier than the stat panel with my interactions with it so far.

**Comment by jlsnow301** [comment]
> Is there any chance this could get a toggle? I personally prefer the stat panel; it takes up space in the UI, it should do something, and as-is it gives you a list of tiles. The new pop-up menu looks aesthetic, but it takes up space in the main game panel where I want to see things, and it makes the stat panel a dead use of space. I dunno how much the maintainers like or dislike preferences, or you care to add a pref, but I'd appreciate it being toggleable.

the goal here is to remove the stat panel

**Comment by Crushtoe** [comment]
> > Is there any chance this could get a toggle? I personally prefer the stat panel; it takes up space in the UI, it should do something, and as-is it gives you a list of tiles. The new pop-up menu looks aesthetic, but it takes up space in the main game panel where I want to see things, and it makes the stat panel a dead use of space. I dunno how much the maintainers like or dislike preferences, or you care to add a pref, but I'd appreciate it being toggleable.
> 
> the goal here is to remove the stat panel

Maybe it's a personal thing but I think it's very hard to replace the stat panel, it's just got so much stuff in it. A simple mob's health is in there (think xenos or morphs), a blob's tiles to defeat, an AI's list of connected cyborgs and their module/integrity/charge/location, the round time and ETA, the current and next map, it's just a really handy... status panel, and it pulls double duty on a lot, including effectively listing turf contents, and it does it without having to load up tgui or anything that could break in a shift.

File: tgui/packages/tgui/interfaces/NtosEmojipedia.tsx [hunk 1]
```diff
@@ -44,15 +44,15 @@ export const NtosEmojipedia = (props) => {
           }
         >
           {filteredEmojis.map((emoji) => (
-            <Image
-              key={emoji.name}
-              m={0}
-              className={classes(['emojipedia16x16', emoji.name])}
-              tooltip={emoji.name}
```
Comment (jlsnow301) [inline tgui/packages/tgui/interfaces/NtosEmojipedia.tsx:51]: sorry guy ya gotta lose the tooltip

**Comment by jlsnow301** [comment]
new icon generation should be near instantaneous. only mobs and complex items will need generated, everything else will be in the asset icon cache

**Comment by dopamiin0** [comment]
> > literally just any status info.
> 
> ESC menu should have this

i dont want to have to hit the escape menu to know my own health as a simplemob

**Comment by jlsnow301** [comment]
> i dont want to have to hit the escape menu to know my own health as a simplemob

noted but unrelated to this

**Comment by Crushtoe** [comment]
Maybe I'm crazy/I'm personally deficient but I feel like the menu is rarely if ever populating with actual icons of any item whatsoever on Sybil. I'm comparing it to Basil where I can alt-click for the status panel style and that panel will be blank initially but populate after I alt-click again if I wait a few seconds for resources to load. The alt-click popup menu never seems to never actually load the sprites in.

**Comment by jlsnow301** [comment]
> Maybe I'm crazy/I'm personally deficient but I feel like the menu is ~rarely if ever~ never populating with actual icons of any item whatsoever on Sybil --- not lockers or walls or items or structures or materials or pipes or anything at all. I'm comparing it to Basil where I can alt-click for the status panel style and that panel will be blank initially but populate after I alt-click again if I wait a few seconds for resources to load. The alt-click popup menu never seems to never actually load the sprites in.

looking into it now, looks like some people are having issues with the 515 image generator, which unfortunately represents 95% of things in the menu.
are they x's or loading spinners?

**Comment by Crushtoe** [comment]
> > Maybe I'm crazy/I'm personally deficient but I feel like the menu is ~rarely if ever~ never populating with actual icons of any item whatsoever on Sybil --- not lockers or walls or items or structures or materials or pipes or anything at all. I'm comparing it to Basil where I can alt-click for the status panel style and that panel will be blank initially but populate after I alt-click again if I wait a few seconds for resources to load. The alt-click popup menu never seems to never actually load the sprites in.
> 
> looking into it now, looks like some people are having issues with the 515 image generator, which unfortunately represents 95% of things in the menu. are they x's or loading spinners?

All X
image

**Comment by jlsnow301** [comment]
> All X

yep, 515... i'll try some fixes

File: code/modules/lootpanel/loot_procs.dm [hunk 2]
```diff
@@ -0,0 +1,171 @@
...
+		if(contents[ref])
+			continue
+
+		RegisterSignals(thing, list(
+			COMSIG_MOVABLE_MOVED,
+			COMSIG_QDELETING,
+			), PROC_REF(on_item_moved))
+
+		var/datum/search_object/item = new(user, thing)
+		found[ref] = item
```
Comment (LemonInTheDark) [inline code/modules/lootpanel/loot_procs.dm:23]: if we register onto QDELETING why do we need a ref for this? also won't it collide?

File: code/modules/lootpanel/loot_procs.dm [hunk 3]
```diff
@@ -0,0 +1,171 @@
...
+
+	if(!user.TurfAdjacent(source_tile))
+		stop_search()
+		return FALSE
+
+	var/atom/thing = obj.item_ref?.resolve()	
+	if(QDELETED(thing))
+		return FALSE
+
+	if(thing != source_tile && (!thing.Adjacent(user) || !locate(thing) in source_tile.contents))
```
Comment (LemonInTheDark) [inline code/modules/lootpanel/loot_procs.dm:77]: reminder that !thing in list is interpreted as (!thing) in list

File: code/modules/lootpanel/loot_procs.dm [hunk 4]
```diff
@@ -0,0 +1,171 @@
...
+
+	var/modifiers = ""
+	if(params["ctrl"])
+		modifiers += "ctrl=1;"
+	if(params["middle"])
+		modifiers += "middle=1;"
+	if(params["shift"])
+		modifiers += "shift=1;"	
+
+	user.ClickOn(thing, modifiers)
```
Comment (LemonInTheDark) [inline code/modules/lootpanel/loot_procs.dm:88]: depression

File: code/modules/lootpanel/search_object.dm [hunk 5]
```diff
@@ -0,0 +1,70 @@
+/**
+ * ## Search Object
+ * An object for content lists. Compacted item data.
+ */
+/datum/search_object
+	/// Client attached to the search_object
+	var/datum/weakref/client_ref
```
Comment (LemonInTheDark) [inline code/modules/lootpanel/search_object.dm:7]: why is this a weakref aren't we in an owning relationship with the thing that deletes us if the client is deleted

File: code/modules/lootpanel/search_object.dm [hunk 6]
```diff
@@ -0,0 +1,70 @@
...
+	/// Weakref to the original object
+	var/datum/weakref/item_ref
```
Comment (LemonInTheDark) [inline code/modules/lootpanel/search_object.dm:9]: similar but with the qdeleting signal

File: code/modules/lootpanel/search_object.dm [hunk 7]
```diff
@@ -0,0 +1,70 @@
...
+	var/string_ref
+
+
+/datum/search_object/New(mob/user, atom/item)
+	. = ..()
+
+	client_ref = WEAKREF(user.client)
+	item_ref = WEAKREF(item)
+	name = item.name
+	path = isobj(item) && item.type
```
Comment (LemonInTheDark) [inline code/modules/lootpanel/search_object.dm:28]: what is item.type doing here

File: code/modules/lootpanel/ss_looting.dm [hunk 8]
```diff
@@ -0,0 +1,41 @@
...
+
+// Iterates over the tile contents for search objects without icons
+/datum/lootpanel/process(seconds_per_tick)
+	var/datum/tgui/panel = SStgui.get_open_ui(user, src)
+	if(isnull(panel))
+		stop_search()
+		return PROCESS_KILL
+
+	var/turf/tile = search_turf_ref?.resolve()
+	if(isnull(tile) || !user.TurfAdjacent(tile))
```
Comment (LemonInTheDark) [inline code/modules/lootpanel/ss_looting.dm:18]: this will never be null

File: code/modules/lootpanel/ss_looting.dm [hunk 9]
```diff
@@ -0,0 +1,41 @@
...
+		stop_search()
+		return PROCESS_KILL
+
+	var/processed = FALSE
+	for(var/ref in contents)
+		CHECK_TICK
```
Comment (LemonInTheDark) [inline code/modules/lootpanel/ss_looting.dm:24]: this is a very bad idea
it risks double processing or even just stacking sleeping procs into infinity

you need to create a subsystem manually that will take a return value from this process call that says "we're done" or "we aren't done"
then create a processing list on this item and clear it out as we handle shit

File: code/modules/lootpanel/ss_looting.dm [hunk 10]
```diff
@@ -0,0 +1,41 @@
...
+			continue
+
+		if(!obj.generate_icon())
+			delete_search_object(obj)
+			continue
+
+		processed = TRUE
+
+	if(processed)
+		return
```
Comment (LemonInTheDark) [inline code/modules/lootpanel/ss_looting.dm:37]: is this for datums with no contents?

**Review by LemonInTheDark — CHANGES_REQUESTED** [review]
not reviewing the JS my brain is too small

File: code/modules/lootpanel/loot_handlers.dm [hunk 11]
```diff
@@ -0,0 +1,46 @@
+/// Item in the tile contents have been moved, update the loot panel if needed
+/datum/lootpanel/proc/on_item_moved(atom/source)
```
[the remark this answers is not in the document]
Comment (LemonInTheDark) [reply code/modules/lootpanel/loot_handlers.dm:2]: ah I think? I understand. still weird but my brain is toasted on 1k line files so s whatever

File: code/modules/lootpanel/loot_procs.dm (hunk 2 above)
Comment (LemonInTheDark) [reply code/modules/lootpanel/loot_procs.dm:23]: is it for the ui?

File: code/modules/lootpanel/loot_procs.dm (hunk 3 above)
Comment (LemonInTheDark) [reply code/modules/lootpanel/loot_procs.dm:77]: oh actually may be wrong here lemme see

Comment (LemonInTheDark) [reply code/modules/lootpanel/loot_procs.dm:77]: this is actually fine but I would appreciate it if you moved the ! to an outer () to avoid people seeing this and assuming it holds true for the other evil in precedence

File: code/modules/lootpanel/loot_handlers.dm [hunk 12]
```diff
@@ -0,0 +1,46 @@
...
+		return
+
+	post_change_callbacks += CALLBACK(src, PROC_REF(on_post_change))
+
+
+/// Reset the search in case there were underlying items
+/datum/lootpanel/proc/on_post_change(turf/new_tile)
+	stop_search()
+	search_turf_ref = WEAKREF(new_tile)
+	start_search()
```
[the remark this answers is not in the document]
Comment (jlsnow301) [reply code/modules/lootpanel/loot_handlers.dm:46]: no, i reset the contents because it might have had hidden items under the top tile

File: code/modules/lootpanel/loot_procs.dm (hunk 2 above)
Comment (jlsnow301) [reply code/modules/lootpanel/loot_procs.dm:23]: yes, basically I maintain a list of search_objects in `contents` to display to the ui. if these items are moved or deleted the ui updates

File: code/modules/lootpanel/loot_procs.dm (hunk 4 above)
Comment (jlsnow301) [reply code/modules/lootpanel/loot_procs.dm:88]: i'm not happy with this either,,,

File: code/modules/lootpanel/loot_handlers.dm (hunk 12 above)
[the remark this answers is not in the document]
Comment (LemonInTheDark) [reply code/modules/lootpanel/loot_handlers.dm:46]: aight

File: code/modules/lootpanel/search_object.dm (hunk 7 above)
Comment (jlsnow301) [reply code/modules/lootpanel/search_object.dm:28]: i'm using the type path to group similar items in the UI

File: code/modules/lootpanel/ss_looting.dm (hunk 10 above)
Comment (jlsnow301) [reply code/modules/lootpanel/ss_looting.dm:37]: the event refires until its out of objects to generate, then it marks searching as done

File: code/modules/lootpanel/search_object.dm (hunk 7 above)
Comment (LemonInTheDark) [reply code/modules/lootpanel/search_object.dm:28]: so path is either FALSE or a typepath?
do you mind using an if block here instead I don't like the mixing of types (I know this is a lot like || but it's new and new things are scary)

File: code/modules/lootpanel/ss_looting.dm (hunk 10 above)
Comment (LemonInTheDark) [reply code/modules/lootpanel/ss_looting.dm:37]: ah I see

Comment (LemonInTheDark) [reply code/modules/lootpanel/ss_looting.dm:37]: (but checktick sleeps right so being half processed should be impossible by this point)

File: code/modules/lootpanel/search_object.dm (hunk 6 above)
Comment (jlsnow301) [reply code/modules/lootpanel/search_object.dm:9]: not sure what you meant here

Comment (LemonInTheDark) [reply code/modules/lootpanel/search_object.dm:9]: we listen for item QDELETING on the lootpanel datum, which owns this datum, and delete this datum when the item is deleted, so why does this need to be a weakref

**Comment by jlsnow301** [comment]
gonna build some unit tests

File: code/modules/lootpanel/ss_looting.dm [hunk 13]
```diff
@@ -0,0 +1,39 @@
...
+
+/datum/controller/subsystem/looting/fire(resumed)
+	if(!length(backlog))
+		return
+
+	if(resumed)
+		processing = backlog.Copy()
+
+	processing = backlog
+	backlog = list()
```
Comment (LemonInTheDark) [inline code/modules/lootpanel/ss_looting.dm:27]:
```suggestion
	if(!resumed)
		processing = backlog
		backlog = list()
```
We don't want to clear out the backlog every time we fire, right?

File: code/modules/lootpanel/ss_looting.dm [hunk 14]
```diff
@@ -0,0 +1,39 @@
...
+		var/datum/lootpanel/panel = processing[length(processing)]
+		if(QDELETED(panel) || !length(panel.to_image))
+			processing.len--
+			continue
+
+		panel.process_images()
+		processing.len--
+
+		if(MC_TICK_CHECK)
+			return
```
Comment (LemonInTheDark) [inline code/modules/lootpanel/ss_looting.dm:39]:
```suggestion
		panel.process_images()
		if(MC_TICK_CHECK)
			return
		processing.len--
```
Because process_images() does a BUNCH of work we're gonna want to allow it to stop midway if it runs out of time.
Sooo let's not always clear out the processing list yeah?

File: code/modules/lootpanel/misc.dm [hunk 15]
```diff
@@ -0,0 +1,39 @@
...
+			")))
+
+			notified = TRUE
+#endif
+
+	populate_contents()
+	ui_interact(owner.mob)
+
+
+/// Used by SSlooting to process images from the to_image list.
```
Comment (LemonInTheDark) [inline code/modules/lootpanel/misc.dm:24]: could you elaborate on what process means? I care less about where this proc is called and more about what it does

File: code/modules/lootpanel/misc.dm [hunk 16]
```diff
@@ -0,0 +1,39 @@
...
+/datum/lootpanel/proc/process_images()
+	for(var/datum/search_object/index as anything in to_image)
+		if(QDELETED(index) || index.icon)
+			to_image -= index
+			continue
+
+		index.generate_icon(owner)
+		to_image -= index
```
Comment (LemonInTheDark) [inline code/modules/lootpanel/misc.dm:32]:
```suggestion
		to_image -= index
		if(TICK_CHECK)
			return
```
You could have this proc return FALSE when it fails to fully complete, and TRUE when it's all the way done. Would make things read a bit better on the subsystem side

File: code/modules/lootpanel/misc.dm [hunk 17]
```diff
@@ -0,0 +1,39 @@
...
+
+	var/datum/tgui/window = SStgui.get_open_ui(owner.mob, src)
+	if(isnull(window))
+		reset_contents()
+		return
+
+	window.send_update()
```
Comment (LemonInTheDark) [inline code/modules/lootpanel/misc.dm:39]: if we want to run these when we do partial work then make the return a break instead

File: code/modules/lootpanel/misc.dm (hunk 16 above)
Comment (LemonInTheDark) [reply code/modules/lootpanel/misc.dm:32]: The idea here is we can have a TON of work all bunched up here, and if we try and do it all we'll eat more cpu then we got rationed.
That means we need to check on our own to see if we've over-consumed, and then hand back control to the subsystem (which will then hand back to the MC)

**Review by LemonInTheDark — CHANGES_REQUESTED** [review]

**Comment by jlsnow301** [comment]
last commit really seems to have fixed broken icon cases

**Comment by jlsnow301** [comment]
Walt gasp

**Comment by ZephyrTFA** [comment]
lgtm

**Comment by ZephyrTFA** [comment]
thanks mobile

**Comment by OverwatchVoice** [comment]
Was this full merged on accident? Without being able to tell the items at a glance, this UI's unusable

**Comment by jlsnow301** [comment]
updating byond should fix this icon issue for you
