### PR TITLE
Fixes the prefs dummy not updating for species features / Bald quirk prefs QoL

### LINKED ISSUE #89768: Changing moth wings + moth antennae on character creation does not update the dummy
- Make a Moth
- Change antennae
   - no update
- Change markings
   - update
- Change wings
   - no update

### LINKED ISSUE #89769: Changing lizard features on character creation does not update the dummy (except going to None)
- Make a lizard
- Change frills, horn. snout, spine, tail...
   - change from a setting to a setting: no update
   - change form a setting to none: update
   - change from none to a setting: update
- Change markings
   - updates

### PR DESCRIPTION
**Pull request by MrMelbert**
## About The Pull Request

image

Fixes #89768
Fixes #89769

- Fixes the prefs menu not updating mobs

Organs are imprinted on insert, and SSwardrobe didn't reset this imprinting status when taking out items.

Weirdly in the past (testing old commits) items withdrawn DID reset imprinting status - or maybe they never set it in the first place?

- Lots of prefs now respect features

`is_accessible` is used when checking many features rather than the prefs menu checking itself in the UI

- Bald quirk QOL

Just handy stuff like showing the wig in the prefs preview, pre-starting with your hat attached

## Changelog

:cl: Melbert
fix: Preference dummy now properly updates when changing some species features
qol: If you have the bald quirk selected, the wig shows up on the preference dummy
qol: If you have the bald quirk selected, and your role starts with a hat, the hat will start attached to your wig
/:cl:

### CODE REVIEW

File: tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferences/MainPage.tsx [hunk 1]
```diff
@@ -512,15 +512,7 @@ export function MainPage(props: MainPageProps) {
...
     ...Object.entries(data.character_preferences.clothing),
-    ...Object.entries(data.character_preferences.features).filter(
-      ([featureName]) => {
-        if (!currentSpeciesData) {
-          return false;
-        }
-
-        return currentSpeciesData.enabled_features.indexOf(featureName) !== -1;
-      },
-    ),
```
Comment (MrMelbert) [inline tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferences/MainPage.tsx:523]: A lot of the primary features never set a `relevant_x` or `relevant_y` (as you can see in the rest of the pr

So theoretically ethereal color, moth wings, lizard parts etc. were all accessible to all species - they just weren't visible from being filtered here
