### PR TITLE
Fixes missing icons in tgui [no gbp]

### LINKED ISSUE #94644: Tgui/vending machine icons and other things just never load some rounds for some reason
### Client Version:

516.1675

### Issue Summary:

Image

Image

Image

UGHHH!!! 0 idea why, tried updating byond version didn't fix it

### Round ID:

[259087](https://statbus.space/round/259087)

### Test Merge Information:

_No response_

### Reproduction Steps:

Open a vending machine (or another round separate from this report a heretic antag panel also failed to load)
Edit: Loadout menu is also effected by this as is ghost observer panel job icons
No Icons load :(

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Should* fix it. 

tgui was set up to not block while waiting on the icon ref map via #90270 (a perf win bc it's huge). However, if the icon ref map's filename hadn't been sent yet, it would error and eventually quit. This simplifies it by directly assigning the icons once we get the asset rather than playing catch.

unrelated but removed vector.ts which was already in tgui-core

## Why It's Good For The Game
Fixes #94644
## Changelog
:cl:
fix: Fixed an issue in TGUI that caused icons to not load sometimes
/:cl:

### CODE REVIEW

File: tgui/packages/common/vector.ts [hunk 1]
```diff
@@ -9,47 +9,38 @@
...
 
 export type Vector = number[];
 
-// It's really not ideal to bypass the type system and use `as Vector`
-// however, there isn't a more eloquent way to type these
-
-export const vecAdd = (...vecs: Vector[]): Vector => {
-  return map(zip<number>(...vecs) as Vector[], (x) => reduce(x, ADD)) as Vector;
-};
+export function vecAdd(...vecs: Vector[]): Vector {
```
Comment (Kashargul) [inline tgui/packages/common/vector.ts]: You can entirely import that file from tgui core as well

Comment (jlsnow301) [reply tgui/packages/common/vector.ts]: we have es-toolkit here. i'd prefer using that as the base. i wasn't sure i wanted tgui core to ship es-toolkit (just yet)

edit: after chewing on it, this benefit is not worth the confusion of having two vectors, so i'll remove this
