### PR TITLE
Fixes black market uplink delivery overflow

### LINKED ISSUE #50822: tgui: Black Market Uplink Cannot Scroll Horizontally

### PR DESCRIPTION
**Pull request by jlsnow301**
## Why It's Good For The Game
Fixes #50822

## Changelog

:cl:
fix: Fixes width on black market uplinks to show three delivery options. Technology!
/:cl:

### CODE REVIEW

File: tgui/packages/tgui/interfaces/BlackMarketUplink.js [hunk 1]
```diff
@@ -114,16 +114,16 @@ const ShipmentSelector = (props, context) => {
...
           if (method.name === 'LTSRBT' && !ltsrbt_built) {
             return null;
           }
           return (
-            <Flex.Item
+            <Stack.Item
               key={method.name}
               mx={1}
-              width="250px">
+              width="17.5rem">
```
Comment (Watermelon914) [inline tgui/packages/tgui/interfaces/BlackMarketUplink.js:126]: How does this look when you resize the UI? You may want to consider using grow instead.

Comment (jlsnow301) [reply tgui/packages/tgui/interfaces/BlackMarketUplink.js:126]: grow won't work here, it causes the elements to stack in a really strange manner. not sure if that's because it's using modal.
here's it, as is, window resized:

Comment (jlsnow301) [reply tgui/packages/tgui/interfaces/BlackMarketUplink.js:126]: using grow:
