### PR TITLE
Destructive Analyzer input fixes and response

### LINKED ISSUE #81705: Can not research alien wirecutters for alien tech
## Issue Summary

When I try to fit alien wirecutters in destructive analyzer/experimentor it doesn't do anything

### PR DESCRIPTION
**Pull request by Bilbo367**
## About The Pull Request

Fixes destructive analyzers to let it get screwed, and accept wire cutters, and emags. Changes some messages to be more helpful.

## Why It's Good For The Game

Closes https://github.com/tgstation/tgstation/issues/81705
Fixes destructive analyzers can now get screwdrivered instead of put it in.
Changes some messages to be more helpful and techinacally correct.

## Changelog

:cl:
fix: destructive analyzers can now get screwdrivered instead of put it in.
fix: destructive analyzer now accepts alien wire cutters, and emags.
/:cl:

### CODE REVIEW

File: tgui/packages/tgui/interfaces/DestructiveAnalyzer.tsx [hunk 1]
```diff
@@ -106,20 +106,21 @@ export const DestructiveAnalyzer = (props) => {
...
-                  : 'This node has already been researched, and does not need to be deconstructed.'
+                  ? 'Deconstruct this to research the selected node.'
+                  : 'This node has already been researched.'
               }
               onClick={() =>
                 act('deconstruct', { deconstruct_id: node.node_id })
               }
-            />
+            >
+              node.node_name
```
Comment (jlsnow301) [inline tgui/packages/tgui/interfaces/DestructiveAnalyzer.tsx:122]: brackets

**Comment by Sadboysuss** [comment]
can they now get doorjacks and emags inserted into them?

**Comment by Bilbo367** [comment]
> can they now get doorjacks and emags inserted into them?

Now it does, but its a bit jank since emags always return success or block on their atom_interact so they never go through the full chain.
