### PR TITLE
Fixes BSA target selection

### LINKED ISSUE #47402: Cannot set target in BSA
Assemble BSA, enable BSA through keycards. Try to target something by pushing the target button -> does nothing.

image

```
Round ID: 122205
BYOND Version: 512.1484
Server revision compiled on: 
Master commit: ac20a47ff97653748c8a46e951f5315bc7c82ff1
The following pull requests are currently test merged:
#46968: 'Kilo Station' by Okand37 at commit 9da473aecf

Local commit: 2dd01611fc063a280a51b66eb81895e6e0177da1
Server tools version: /tg/station 13 Server v3.2.6.2
```

### PR DESCRIPTION
**Pull request by actioninja**
## About The Pull Request

You can select targets with BSA again.
I fucked up case.
Fixes #47402 

Also some cleanup of this file with box props.

## Changelog
:cl:
fix: bsa can pick targets again (again)
/:cl:

### CODE REVIEW

File: tgui-next/packages/tgui/interfaces/BluespaceArtillery.js [hunk 1]
```diff
@@ -6,53 +6,55 @@ export const BluespaceArtillery = props => {
...
         <Fragment>
           <Section
             title="Target"
             buttons={(
               <Button
                 icon="crosshairs"
-                disabled={!data.unlocked}
-                onclick={() => act(ref, 'recalibrate')} />
+                disabled={!unlocked}
+                onClick={() => act(ref, 'recalibrate')} />
```
Comment (actioninja) [inline tgui-next/packages/tgui/interfaces/BluespaceArtillery.js]: this is the actual fix
