### PR TITLE
Fixes some miscapitalization of Nanotrasen 

### LINKED ISSUE #75019: Traitor posters spell Nanotrasen wrong
## Reproduction:

At least one of the traitor posters spells Nanotrasen wrong, it says NanoTrasen.

I am not sure if it's all of them but at least the "NanoTrasen Neural Statistics" poster spells it wrong in title and description. It may be an issue with all of them.

### PR DESCRIPTION
**Pull request by E231kei500bandai**
## About The Pull Request

Fixes #75019

Also fixes it in a drink, the ethereal lore, and some photocopier paperwork.

And also adds "NanoTrasen" to common spelling mistakes

## Why It's Good For The Game

Nanotrasen is the correct capitalization
## Changelog
:cl:
spellcheck: Fixed Nanotrasen being miscapitalized in traitor posters, a drink, the ethereal lore, and some photocopier paperwork
/:cl:

### CODE REVIEW

**Comment by Mothblocks** [comment]
Can you add this to https://github.com/tgstation/tgstation/blob/master/tools/ci/check_grep.sh with out "Nanotransen" typo?

**Comment by BlueMemesauce** [comment]
> Can you add this to https://github.com/tgstation/tgstation/blob/master/tools/ci/check_grep.sh with out "Nanotransen" typo? You would `$grep 'NanoTrasen'` with no `-i`

i'm not really sure what you meant by "with out"
do you mean i should put both?

**Comment by Mothblocks** [comment]
*our :)

File: tools/ci/check_grep.sh [hunk 1]
```diff
@@ -161,9 +162,10 @@ if $grep -i 'centcomm' $code_files; then
     echo -e "${RED}ERROR: Misspelling(s) of CentCom detected in code, please remove the extra M(s).${NC}"
     st=1
 fi;
-if $grep 'NanoTrasen' $code_files; then
+if $grep -ni 'nanotransen' $code_files
+	$grep 'NanoTrasen' $code_files; then
```
Comment (Mothblocks) [inline tools/ci/check_grep.sh:166]: I don't trust that trying to combine these works. Make a separate thing

**Comment by BlueMemesauce** [comment]
sorry I should have done the test on a separate branch cause it requested all those reviewers but might as well do it here now

File: tools/ci/check_grep.sh [hunk 2]
```diff
@@ -82,6 +82,11 @@ if $grep -i 'nanotransen' $map_files; then
     echo -e "${RED}ERROR: Misspelling of Nanotrasen detected in maps, please remove the extra N(s).${NC}"
     st=1
 fi;
+if $grep 'NanoTrasen' $map_files; then
+	echo
+    echo -e "${RED}ERROR: Misspelling of Nanotrasen detected in maps, please uncapitalize the T(s).${NC}"
```
Comment (san7890) [inline tools/ci/check_grep.sh:87]:
```suggestion
    echo -e "${RED}ERROR: Misspelling of Nanotrasen detected in maps, please uncapitalize the T.${NC}"
```

there's only one T in Nanotrasen.

File: tools/ci/check_grep.sh [hunk 3]
```diff
@@ -166,6 +171,11 @@ if $grep -ni 'nanotransen' $code_files; then
     echo -e "${RED}ERROR: Misspelling(s) of Nanotrasen detected in code, please remove the extra N(s).${NC}"
     st=1
 fi;
+if $grep 'NanoTrasen' $code_files; then
+	echo
+    echo -e "${RED}ERROR: Misspelling(s) of Nanotrasen detected in code, please uncapitalize the T(s).${NC}"
```
Comment (san7890) [inline tools/ci/check_grep.sh:176]:
```suggestion
    echo -e "${RED}ERROR: Misspelling(s) of Nanotrasen detected in code, please uncapitalize the T.${NC}"
```

**Review by san7890 — CHANGES_REQUESTED** [review]
huge nit but it's kinder

File: tools/ci/check_grep.sh (hunk 2 above)
Comment (BlueMemesauce) [reply tools/ci/check_grep.sh:87]: I made it the same as the above `Misspelling of Nanotrasen detected in maps, please remove the extra N(s).`
It's referring to the fact that there can be multiple mispellings in the code that have to be removed, it doesn't mean a single example of it has multiple Ns/capital Ts.

Comment (san7890) [reply tools/ci/check_grep.sh:87]: the grep error will spit itself out multiple times every time it finds an example of an error:
image

via #67173

Comment (san7890) [reply tools/ci/check_grep.sh:87]: or well it should, let me recheck

Comment (BlueMemesauce) [reply tools/ci/check_grep.sh:87]: Okay I'll fix the above one too then

Comment (san7890) [reply tools/ci/check_grep.sh]: image

ahhhh they changed it on me or i have dementia, either way nvm

Comment (san7890) [reply tools/ci/check_grep.sh]: @BlueMemesauce lol revert that last commit it's my bad because the format makes it a lot more clear now

Comment (BlueMemesauce) [reply tools/ci/check_grep.sh]: Okay it doesn't, see https://github.com/BlueMemesauce/tgstation/actions/runs/4842310387/jobs/8629175983?pr=1

Comment (BlueMemesauce) [reply tools/ci/check_grep.sh]: sorry github is being slow to refresh unless you do it manually but yea
