### PR TITLE
Fixes Pull Request announcements not working in certain situations

### LINKED ISSUE #26240: [Might not be an issue] PRs aren't announcing in game
Yes my option for PRs is enabled. Not sure why they're not announcing but they're not.

### PR DESCRIPTION
**Pull request by MrsTonedOne**
@Cyberboss (It wasn't your fault for once)

fixes #26240

Caused by #24008

### CODE REVIEW

File: tools/github_webhook_processor.php [hunk 1]
```diff
@@ -423,21 +423,20 @@ function checkchangelog($payload, $merge = false, $compile = true) {
 
 function sendtoallservers($str, $payload = null) {
 	global $servers;
-	
+	if (!empty($payload))
+		$str .= '&payload='.urlencode(json_encode($payload));
 	foreach ($servers as $serverid => $server) {
+		$msg = $str;
 		if (isset($server['comskey']))
-			$str .= '&key='.urlencode($server['comskey']);
```
Comment (MrStonedOne) [inline tools/github_webhook_processor.php]: This line was the primary cause. it added the coms key to the $str, so there would be two coms keys, and byond would turn key into a list, and `/list(2)` `!=` `config.comskey`
