### PR TITLE
Typescript refactor for Number Input

### LINKED ISSUE #80971: NumberInput autoselect is broken
## Issue Summary

Due to the react change, NumberInputs no longer have their number autoselected when you click on them.

@SyncIt21 @jlsnow301 new issue on my actual acc.

## Reproduction:

Just click any NumberInput like the temperature on a reaction chamber and observe the lack of autoselect.

### LINKED ISSUE #81379: Selecting numbers in tgui is clunky
Reporting client version: 515.1630

## Issue Summary
When selecting numbers in the tgui (namely "Edit Filters" and "Edit Color as Matrix" panels), you have to press M1 again to be able to edit the number in the slot.
You can only "drag" the values in that slot up or down before selecting it.

## Round ID:
[223646](https://scrubby.melonmesa.com/round/223646)

## Reproduction:
-Open Edit Color Matrix Panel;
-Click on a random number to edit it;
-The number turns white and typing doesn't change it. Furthermore, you can no longer drag the slot up or down with your mouse to change the value without typing it;
-Click again on said slot to select it and then type in it.

Basically, you gotta click twice in order to edit numbers in some tgui

The thick red lines are around the "selected" slots (which have to be clicked again to edit), and the thin green lines are around the non-selected slots:
imagem
imagem

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request
- Fixes #80971
- Fixes #81379

You now only click once to highlight & edit the value. Converted NumberInput to typescript

## Changelog
:cl:
fix: NumberInput(used in chem heater, plumbing reaction chamber etc) highlighting & editing requires only single click like before
refactor: Typescript conversion for NumberInput TGUI Component
/:cl:

### CODE REVIEW

File: tgui/packages/tgui/components/NumberInput.tsx [hunk 1]
```diff
@@ -0,0 +1,351 @@
...
+  MouseEventHandler,
+  RefObject,
+} from 'react';
+
+import { AnimatedNumber } from './AnimatedNumber';
+import { Box } from './Box';
+
+const DEFAULT_UPDATE_RATE = 400;
+
+type NumberInputProps = {
```
Comment (jlsnow301) [inline tgui/packages/tgui/components/NumberInput.tsx:18]: these should be just "props" and "state" unless we're working with multiple components in one file. this is to avoid type names getting overly complex and certainly resembling java (this kills the crab)

File: tgui/packages/tgui/components/NumberInput.tsx [hunk 2]
```diff
@@ -0,0 +1,351 @@
...
+  unit?: string;
+  height?: string;
+  width?: string;
+  lineHeight?: string;
+  fontSize?: string;
+  updateRate?: number;
+  format?: (value: number) => string;
+  onChange?: (e: any, value: number) => void;
+  onDrag?: (e: any, value: number) => void;
+};
```
Comment (jlsnow301) [inline tgui/packages/tgui/components/NumberInput.tsx:39]: there's a helper for this that can make it neater, and we should use it to avoid chaining so many ?s

```tsx
type Props = {
... 
} & Partial<{ // optionals
step: number;
...
};
```

File: tgui/packages/tgui/components/NumberInput.tsx [hunk 3]
```diff
@@ -0,0 +1,351 @@
...
+    });
+
+    if (dragging) {
+      this.suppressFlicker();
+      if (onChange) {
+        onChange(event, value);
+      }
+      if (onDrag) {
+        onDrag(event, value);
+      }
```
Comment (jlsnow301) [inline tgui/packages/tgui/components/NumberInput.tsx:181]: shave off some lines doing this here and elsewhere
```suggestion
      onChange?.(event, value);
      onDrag?.(event, value); 
```

File: tgui/packages/tgui/components/NumberInput.tsx [hunk 4]
```diff
@@ -0,0 +1,351 @@
...
+      if (input) {
+        input.value = `${internalValue}`;
+        // IE8: Dies when trying to focus a hidden element
+        // (Error: Object does not support this action)
+        setTimeout(() => {
+          try {
+            input.focus();
+            input.select();
+          } catch {}
+        }, 1);
```
Comment (jlsnow301) [inline tgui/packages/tgui/components/NumberInput.tsx:193]: we no longer use ie8 so this might not be valid

File: tgui/packages/tgui/components/NumberInput.tsx [hunk 5]
```diff
@@ -0,0 +1,351 @@
...
+      return;
+    }
+
+    if (event.key === KEY.Enter) {
+      const targetValue = clamp(
+        parseFloat(event.currentTarget.value),
+        minValue,
+        maxValue,
+      );
+      if (Number.isNaN(targetValue)) {
```
Comment (jlsnow301) [inline tgui/packages/tgui/components/NumberInput.tsx:241]: i think isNaN is part of the standard library - do we need the `Number.` part? correct me if I'm wrong here pls

**Review by jlsnow301 — COMMENTED** [review]
good step in the right direction. one day this should be made into a functional component.

**Comment by SyncIt21** [comment]
Hi @jlsnow301 :). It's been a while since we last saw you on the repo, good to have you back.

File: tgui/packages/tgui/components/NumberInput.tsx (hunk 2 above)
Comment (SyncIt21) [reply tgui/packages/tgui/components/NumberInput.tsx:39]: I have a problem. after using partial i ran into this
Screenshot (397)
How do i declare prop types?

Comment (SyncIt21) [reply tgui/packages/tgui/components/NumberInput.tsx:39]: Never mind. Fixed it by using `Require<{}> & Partial<{}>`

File: tgui/packages/tgui/components/NumberInput.tsx (hunk 5 above)
Comment (SyncIt21) [reply tgui/packages/tgui/components/NumberInput.tsx]: Yup Number. is not required 👍

File: tgui/packages/tgui/components/NumberInput.tsx [hunk 6]
```diff
@@ -0,0 +1,337 @@
...
+import { AnimatedNumber } from './AnimatedNumber';
+import { Box } from './Box';
+
+const DEFAULT_UPDATE_RATE = 400;
+
+type Props = Required<{
+  value: number | string;
+  minValue: number;
+  maxValue: number;
+}> &
```
Comment (jlsnow301) [inline tgui/packages/tgui/components/NumberInput.tsx:22]:
```suggestion
type Props = {
  value: number | string;
  minValue: number;
  maxValue: number;
} &
```
required is default behavior - you'd use this utility to make all the properties of an existing type required, but has no effect here

Comment (SyncIt21) [reply tgui/packages/tgui/components/NumberInput.tsx:22]: Actually I need this because https://github.com/tgstation/tgstation/pull/81913#discussion_r1518801437

Typescript be bugging :(

File: tgui/packages/tgui/components/NumberInput.tsx (hunk 2 above)
Comment (jlsnow301) [reply tgui/packages/tgui/components/NumberInput.tsx]: This does look like a bug! Does it still give a compiler error if you type it as
defaultProps: Props?

Comment (SyncIt21) [reply tgui/packages/tgui/components/NumberInput.tsx]: No luck :( .
