### PR TITLE
Fixes circuit bluescreens

### LINKED ISSUE #80437: Several circuit GUI bluescreens
## Issue Summary
Several bluescreens that make it very difficult to use circuits. Figured I'd put them in one report since they're sorta in the same place, but I can split it up if that would be more convenient.

## Round ID:
N/A, tested on local but with #80410 merged

## Testmerges:
#80410

## Reproduction:
<details>
<summary>Use the plus button after linking the circuit to the component printer, to try and add a component</summary>

```
TypeError: Unable to get property 'component' of undefined or null reference
   at render (http://127.0.0.1:61452/tgui.bundle.js:82698:9)
   at finishClassComponent (http://127.0.0.1:61452/tgui.bundle.js:17476:21)
   at updateClassComponent (http://127.0.0.1:61452/tgui.bundle.js:17434:13)
   at beginWork (http://127.0.0.1:61452/tgui.bundle.js:18982:25)
   at callCallback (http://127.0.0.1:61452/tgui.bundle.js:4421:25)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"flufflesthedog","interface":"IntegratedCircuit","window":{"key":"[0x200a637]-main","size":null,"fancy":1,"locked":0}}

TypeError: Unable to get property 'component' of undefined or null reference
   at render (http://127.0.0.1:61452/tgui.bundle.js:82698:9)
   at finishClassComponent (http://127.0.0.1:61452/tgui.bundle.js:17476:21)
   at updateClassComponent (http://127.0.0.1:61452/tgui.bundle.js:17434:13)
   at beginWork (http://127.0.0.1:61452/tgui.bundle.js:18982:25)
   at callCallback (http://127.0.0.1:61452/tgui.bundle.js:4421:25)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"flufflesthedog","interface":"IntegratedCircuit","window":{"key":"[0x200a637]-main","size":null,"fancy":1,"locked":0}}

TypeError: Unable to get property 'component' of undefined or null reference
   at render (http://127.0.0.1:61452/tgui.bundle.js:82698:9)
   at finishClassComponent (http://127.0.0.1:61452/tgui.bundle.js:17476:21)
   at updateClassComponent (http://127.0.0.1:61452/tgui.bundle.js:17434:13)
   at beginWork (http://127.0.0.1:61452/tgui.bundle.js:18982:25)
   at callCallback (http://127.0.0.1:61452/tgui.bundle.js:4421:25)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"flufflesthedog","interface":"IntegratedCircuit","window":{"key":"[0x200a637]-main","size":null,"fancy":1,"locked":0}}

TypeError: Unable to get property 'component' of undefined or null reference
   at render (http://127.0.0.1:61452/tgui.bundle.js:82698:9)
   at finishClassComponent (http://127.0.0.1:61452/tgui.bundle.js:17476:21)
   at updateClassComponent (http://127.0.0.1:61452/tgui.bundle.js:17434:13)
   at beginWork (http://127.0.0.1:61452/tgui.bundle.js:18982:25)
   at callCallback (http://127.0.0.1:61452/tgui.bundle.js:4421:25)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"flufflesthedog","interface":"IntegratedCircuit","window":{"key":"[0x200a637]-main","size":null,"fancy":1,"locked":0}}

TypeError: Unable to get property 'component' of undefined or null reference
   at render (http://127.0.0.1:61452/tgui.bundle.js:82698:9)
   at finishClassComponent (http://127.0.0.1:61452/tgui.bundle.js:17476:21)
   at updateClassComponent (http://127.0.0.1:61452/tgui.bundle.js:17434:13)
   at beginWork (http://127.0.0.1:61452/tgui.bundle.js:18982:25)
   at callCallback (http://127.0.0.1:61452/tgui.bundle.js:4421:25)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"flufflesthedog","interface":"IntegratedCircuit","window":{"key":"[0x200a637]-main","size":null,"fancy":1,"locked":0}}

TypeError: Unable to get property 'component' of undefined or null reference
   at render (http://127.0.0.1:61452/tgui.bundle.js:82698:9)
   at finishClassComponent (http://127.0.0.1:61452/tgui.bundle.js:17476:21)
   at updateClassComponent (http://127.0.0.1:61452/tgui.bundle.js:17434:13)
   at beginWork (http://127.0.0.1:61452/tgui.bundle.js:18982:25)
   at callCallback (http://127.0.0.1:61452/tgui.bundle.js:4421:25)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"flufflesthedog","interface":"IntegratedCircuit","window":{"key":"[0x200a637]-main","size":null,"fancy":1,"locked":0}}

UnhandledRejection: TypeError: Unable to get property 'component' of undefined or null reference
   at render (http://127.0.0.1:61452/tgui.bundle.js:82698:9)
   at finishClassComponent (http://127.0.0.1:61452/tgui.bundle.js:17476:21)
   at updateClassComponent (http://127.0.0.1:61452/tgui.bundle.js:17434:13)
   at beginWork (http://127.0.0.1:61452/tgui.bundle.js:18982:25)
   at beginWork$1 (http://127.0.0.1:61452/tgui.bundle.js:23688:21)
   at performUnitOfWork (http://127.0.0.1:61452/tgui.bundle.js:22992:17)
   at workLoopSync (http://127.0.0.1:61452/tgui.bundle.js:22918:17)
   at renderRootSync (http://127.0.0.1:61452/tgui.bundle.js:22895:21)
   at performSyncWorkOnRoot (http://127.0.0.1:61452/tgui.bundle.js:22599:13)
   at flushSyncCallbacks (http://127.0.0.1:61452/tgui.bundle.js:11099:29)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"flufflesthedog","interface":"IntegratedCircuit","window":{"key":"[0x200a637]-main","size":null,"fancy":1,"locked":0}}
```
</details>

<details>
<summary>Try to drag and drop a variable setter/getter into the circuit</summary>

```
TypeError: Unable to get property 'component' of undefined or null reference
   at render (http://127.0.0.1:61452/tgui.bundle.js:82698:9)
   at finishClassComponent (http://127.0.0.1:61452/tgui.bundle.js:17476:21)
   at updateClassComponent (http://127.0.0.1:61452/tgui.bundle.js:17434:13)
   at beginWork (http://127.0.0.1:61452/tgui.bundle.js:18982:25)
   at callCallback (http://127.0.0.1:61452/tgui.bundle.js:4421:25)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"flufflesthedog","interface":"IntegratedCircuit","window":{"key":"[0x200a637]-main","size":null,"fancy":1,"locked":0}}

TypeError: Unable to get property 'component' of undefined or null reference
   at render (http://127.0.0.1:61452/tgui.bundle.js:82698:9)
   at finishClassComponent (http://127.0.0.1:61452/tgui.bundle.js:17476:21)
   at updateClassComponent (http://127.0.0.1:61452/tgui.bundle.js:17434:13)
   at beginWork (http://127.0.0.1:61452/tgui.bundle.js:18982:25)
   at beginWork$1 (http://127.0.0.1:61452/tgui.bundle.js:23688:21)
   at performUnitOfWork (http://127.0.0.1:61452/tgui.bundle.js:22992:17)
   at workLoopSync (http://127.0.0.1:61452/tgui.bundle.js:22918:17)
   at renderRootSync (http://127.0.0.1:61452/tgui.bundle.js:22895:21)
   at performSyncWorkOnRoot (http://127.0.0.1:61452/tgui.bundle.js:22599:13)
   at flushSyncCallbacks (http://127.0.0.1:61452/tgui.bundle.js:11099:29)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"flufflesthedog","interface":"IntegratedCircuit","window":{"key":"[0x200a637]-main","size":null,"fancy":1,"locked":0}}

TypeError: Unable to get property 'x' of undefined or null reference
   at handleVarDropped (http://127.0.0.1:61452/tgui.bundle.js:84307:9)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"flufflesthedog","interface":"IntegratedCircuit","window":{"key":"[0x200a637]-main","size":null,"fancy":1,"locked":0}}
```
</details>

<details>
<summary>Use the extra configuration button on an access checker component</summary>

```
TypeError: Unable to get property 'includes' of undefined or null reference
   at checkAccessIcon (http://127.0.0.1:61452/tgui.bundle.js:149843:13)
   at Anonymous function (http://127.0.0.1:61452/tgui.bundle.js:149886:29)
   at Anonymous function (http://127.0.0.1:61452/tgui.bundle.js:155976:13)
   at map (http://127.0.0.1:61452/tgui.bundle.js:163662:9)
   at AccessConfig (http://127.0.0.1:61452/tgui.bundle.js:149857:5)
   at renderWithHooks (http://127.0.0.1:61452/tgui.bundle.js:14520:13)
   at mountIndeterminateComponent (http://127.0.0.1:61452/tgui.bundle.js:17730:17)
   at beginWork (http://127.0.0.1:61452/tgui.bundle.js:18963:25)
   at callCallback (http://127.0.0.1:61452/tgui.bundle.js:4421:25)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"flufflesthedog","interface":"CircuitAccessChecker","window":{"key":"[0x2020956]-main","size":null,"fancy":1,"locked":0}}

TypeError: Unable to get property 'includes' of undefined or null reference
   at checkAccessIcon (http://127.0.0.1:61452/tgui.bundle.js:149843:13)
   at Anonymous function (http://127.0.0.1:61452/tgui.bundle.js:149886:29)
   at Anonymous function (http://127.0.0.1:61452/tgui.bundle.js:155976:13)
   at map (http://127.0.0.1:61452/tgui.bundle.js:163662:9)
   at AccessConfig (http://127.0.0.1:61452/tgui.bundle.js:149857:5)
   at renderWithHooks (http://127.0.0.1:61452/tgui.bundle.js:14520:13)
   at mountIndeterminateComponent (http://127.0.0.1:61452/tgui.bundle.js:17730:17)
   at beginWork (http://127.0.0.1:61452/tgui.bundle.js:18963:25)
   at beginWork$1 (http://127.0.0.1:61452/tgui.bundle.js:23688:21)
   at performUnitOfWork (http://127.0.0.1:61452/tgui.bundle.js:22992:17)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"flufflesthedog","interface":"CircuitAccessChecker","window":{"key":"[0x2020956]-main","size":null,"fancy":1,"locked":0}}
```
</details>

### LINKED ISSUE #80491: adding circuit components from inside the circuit bluescreens
Reporting client version: 515.1620

## Issue Summary

after you use a circuit on a component printer you are supposed to be able to go into it and print the parts from the circuit itself to save time printing them all individualy but for the past week or so doing that and trying to open the menu that lets you add components just bluesceens the menu

## Round ID:
[220847](https://scrubby.melonmesa.com/round/220847)

## Testmerges:
- [Increase TGUI connection lost threshold](https://www.github.com/tgstation/tgstation/pull/80304)
- [Refactors TS in Box component](https://www.github.com/tgstation/tgstation/pull/80368)

## Reproduction:
get circuit. use circuit on component printer. open circuit. click the "+" near the name part in the topleft. bluescreen.

here is what it prints out 
`UnhandledRejection:` TypeError: Unable to get property 'component' of undefined or null reference
   at u.render (https://tgstation13.download/byond/assets/1d/asset.1d51fb6d98092a556e01bc323e346c37.js:279:349338)
   at hl (https://tgstation13.download/byond/assets/1d/asset.1d51fb6d98092a556e01bc323e346c37.js:9:80524)
   at $c (https://tgstation13.download/byond/assets/1d/asset.1d51fb6d98092a556e01bc323e346c37.js:9:80374)
   at _u (https://tgstation13.download/byond/assets/1d/asset.1d51fb6d98092a556e01bc323e346c37.js:9:119950)
   at vu (https://tgstation13.download/byond/assets/1d/asset.1d51fb6d98092a556e01bc323e346c37.js:9:114785)
   at id (https://tgstation13.download/byond/assets/1d/asset.1d51fb6d98092a556e01bc323e346c37.js:9:114719)
   at xs (https://tgstation13.download/byond/assets/1d/asset.1d51fb6d98092a556e01bc323e346c37.js:9:114572)
   at hu (https://tgstation13.download/byond/assets/1d/asset.1d51fb6d98092a556e01bc323e346c37.js:9:111598)
   at co (https://tgstation13.download/byond/assets/1d/asset.1d51fb6d98092a556e01bc323e346c37.js:9:48533)
   at Bi (https://tgstation13.download/byond/assets/1d/asset.1d51fb6d98092a556e01bc323e346c37.js:9:108897)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"noodlenoms","interface":"IntegratedCircuit","window":{"key":"[0x200b117]-main","size":null,"fancy":1,"locked":0}}`

### LINKED ISSUE #80526: Circuits don't work
## Issue Summary
When you open up a circuit and it's "+", if you have linked it to a circuit imprinter, you will get a fatal exeception error.

## Round ID:
Don't remember, but it has happened multiple times.

## Reproduction:

Grap circuit board
Link circuit board to imprinter
Open up circuit board
Press the plus button at the top
Watch it blue screen

### PR DESCRIPTION
**Pull request by Watermelon914**
## About The Pull Request
This is a quick fix to the circuit bluescreens found in this issue report #80437

Circuit UI is still looking funky, likely due to the inferno -> react switch.
Will probably need to clean it up and/or refactor to do a proper fix on it.

Closes #80437 #80491 #80526

## Why It's Good For The Game
Bugfix

## Changelog
:cl:
fix: Fixed integrated circuit UI breaking.
/:cl:

### CODE REVIEW

File: tgui/packages/tgui/interfaces/CircuitAccessChecker.tsx [hunk 1]
```diff
@@ -28,8 +28,8 @@ export const CircuitAccessChecker = (props) => {
           </LabeledList.Item>
         </LabeledList>
         <AccessConfig
-          accesses={regions}
-          selectedList={accesses}
+          accesses={regions || []}
+          selectedList={accesses || []}
```
Comment (jlsnow301) [inline tgui/packages/tgui/interfaces/CircuitAccessChecker.tsx:32]: these should already be casted in L16. what's going on here?

Comment (Watermelon914) [reply tgui/packages/tgui/interfaces/CircuitAccessChecker.tsx:32]: Apparently not, it just bluescreens.
It's possible that those are getting overriden by the fact that these values may be null, not undefined.
Idk if react will take values if null is passed in, I know it won't if it's undefined.
