### PR TITLE
Fix categories in preferences menu

### LINKED ISSUE #90652: Game preferences window category buttons don't work
### Client Version:

516.1659

### Issue Summary:

The category buttons at the top of the Game Preferences window don't bring the menu to the desired section in preferences.

Image

### Round ID:

_No response_

### Test Merge Information:

_No response_

### Reproduction Steps:

Hit any of the Game Preferences category buttons

### PR DESCRIPTION
**Pull request by AyIong**
## About The Pull Request
Fixes categories navigation in prefs and transfer it to FC
Closes #90652

## Why It's Good For The Game
Less bugs
TS tells me to go fuck myself on this use of `ref` in `Stack.Item`, so I used `div`
It works, but I have very little experience with refs, so I hope I did it right

https://github.com/user-attachments/assets/34e1b042-eab5-4d90-a707-7bfeb37af1bc

## Changelog

:cl:
fix: Navigating to categories in preferences works again
/:cl:

### CODE REVIEW

**Comment by lessthnthree** [comment]
Closes https://github.com/tgstation/tgstation/issues/90652

File: tgui/packages/tgui/interfaces/PreferencesMenu/GamePreferences/TabbedMenu.tsx [hunk 1]
```diff
@@ -1,94 +1,71 @@
...
-    );
-  }
+      <Stack.Item
+        grow
+        ref={sectionRef}
+        position="relative"
+        overflowY="scroll"
+        {...{
+          ...props.contentProps,
+        }}
```
Comment (jlsnow301) [inline tgui/packages/tgui/interfaces/PreferencesMenu/GamePreferences/TabbedMenu.tsx:52]: will ...props.contentProps work here? looks like an extra destructure for no raisin

File: tgui/packages/tgui/interfaces/PreferencesMenu/GamePreferences/TabbedMenu.tsx [hunk 2]
```diff
@@ -1,94 +1,71 @@
...
-  sectionRef: RefObject<HTMLDivElement | null> = createRef();
+export function TabbedMenu(props: TabbedMenuProps) {
+  const sectionRef = useRef<HTMLDivElement>(null);
+  const categoryRefs = useRef<Record<string, HTMLDivElement | null>>({});
 
-  getCategoryRef(category: string): RefObject<HTMLDivElement | null> {
-    if (!this.categoryRefs[category]) {
-      this.categoryRefs[category] = createRef();
-    }
+  console.log(categoryRefs);
```
Comment (jlsnow301) [inline tgui/packages/tgui/interfaces/PreferencesMenu/GamePreferences/TabbedMenu.tsx:13]:
```suggestion
```
:o

File: tgui/packages/tgui/interfaces/PreferencesMenu/GamePreferences/TabbedMenu.tsx (hunk 1 above)
Comment (AyIong) [reply tgui/packages/tgui/interfaces/PreferencesMenu/GamePreferences/TabbedMenu.tsx:51]: Yeah, that work's
For a font size

Comment (jlsnow301) [reply tgui/packages/tgui/interfaces/PreferencesMenu/GamePreferences/TabbedMenu.tsx:51]: i mean it's creating an additional object, this could be written `{ ... props.contentProps }`
