### PR TITLE
Fixes TextArea lag

### LINKED ISSUE #25684: Text input into character preference fields laggy, frequently eatten
Reporting client version: 514.1589

## Issue Summary

Inputting text into the fields in the character panel are horribly laggy, and inputs are frequently eaten up making inline editing practically impossible. This is not ideal. Pasting text is fine, naturally. ~~While the Opfor panel is currently broken, people were commenting on that being the same, too.~~ This is a very recent change. More or less, it's acting as shitty as paperwork is. Verbs like subtler are just fine and dandy, oddly enough.

It's an off the cuff guess, but I think it might have something to do with #25620 as I believe this started _after_ the tgui changes.

## Round ID:
10162

## Testmerges:
- [Plant Tank](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25328)
- [LOOC'ing while in crit..? Or while unconscious..? You got it!](https://github.com/Skyrat-SS13/Skyrat-tg/pull/25506)

## Reproduction:

idk, type something. If it's some weird lag issue it's possible it won't trigger on a local host.

### PR DESCRIPTION
**Pull request by vinylspiders**
## About The Pull Request

Fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/25684
Helps with https://github.com/tgstation/tgstation/issues/80468 (maybe?)

This should fix the lag in the TextArea input boxes.

<details><summary>Before</summary>

MdbjaR3hDc

</details>

<details><summary>After</summary>

7aOoVFa76R

</details>

## Why It's Good For The Game

Fixes laggy UIs.

## Changelog

:cl:
fix: reduces lag in the tgui textarea input boxes
/:cl:

### CODE REVIEW

File: tgui/packages/tgui/components/TextArea.tsx [hunk 1]
```diff
@@ -67,7 +70,7 @@ export const TextArea = forwardRef(
     const handleKeyDown = (event: KeyboardEvent<HTMLTextAreaElement>) => {
       if (event.key === KEY.Enter) {
         if (event.shiftKey) {
-          onChange?.(event as any, event.currentTarget.value);
+          event.currentTarget.focus();
```
Comment (jlsnow301) [inline tgui/packages/tgui/components/TextArea.tsx:73]: why is this behavior changing? it should keep onInput but does it need to focus? the idea is that it starts a new line
