### PR TITLE
Fix reconnect issue during roundrestart

### LINKED ISSUE #53213: The game rarely automatically reconnects anymore.
## Reproduction:

Be connected when a round ends, wait.
More times than not, it does not reconnect you automatically anymore. You have to do it manually.
Multiple people confirm the same is true for them.

Possibly related to TGChat?

### LINKED ISSUE #54131: Auto reconnect does no longer reconnect at end of round
## Round ID:
[147446](https://scrubby.melonmesa.com/round/147446)

## Testmerges:
#53596: 'Removes Admin Stickyban Exemption Workaround' by bobbahbrown at commit adbee092e4
#53965: 'Tanks have tiers' by Ghilker at commit 8328b2ad36

## Reproduction:
1. end round
2. reconnect doesn't happen

Auto reconnect does no longer reconnect at end of round

### LINKED ISSUE #55301: Tgchat panel freezes on reconnect
Reporting client version: 513.1536

## Round ID:
[151375](https://scrubby.melonmesa.com/round/151375)

## Testmerges:
- [Creates Datumized AI and applies it to monkeys](https://www.github.com/tgstation/tgstation/pull/55238)

## Reproduction:
1. Wait for round to end while connected
2. Don't reconnect immediately
3. A few minutes later, connect, tgchat will remain the exact same as it was prior to reconnecting despite having successfully reconnected. No new messages are shown.

Reproduction is not consistent, seems rare. I've only just encountered this for the first time now. May be related to #54692.

The tgchat panel itself becomes non-responsive, with a loading icon shown on the cursor when the panel itself is moused over. No buttons can be pressed, no UI element on the tgchat window can be clicked on. No messages are added or removed, nothing is cleared, it just remains as it was prior to reconnecting.

image

### PR DESCRIPTION
**Pull request by stylemistake**
## About The Pull Request

> Fixes #54131
> Fixes #53213
> Fixes #55301 (unless it's something different, then reopen)

I have confirmed that this was a BYOND issue.

TGchat makes topic calls to calculate ping, and if ping is issued in the middle of reconnect, it confuses Dreamseeker and it causes the connection to crash.

image

The reason why reconnect worked **sometimes** is exactly because of the pings, because they were sent every second, and it was totally possible to reconnect in between those pings.

**This does not fix manually initiated reconnects**.

This also fixes `You are either AFK, experiencing lag or the connection has closed.` message during roundrestart.

## Changelog
:cl:
fix: IMPORTANT FIX: Game client will now properly reconnect on roundrestart!!!
/:cl:

### CODE REVIEW

**Comment by Qustinnus** [comment]
as the kids these days say, very pog.

**Comment by Jared-Fogle** [comment]
do u have a paypal

**Review by Mothblocks — APPROVED** [review]

File: tgui/packages/tgui-panel/ping/middleware.js [hunk 1]
```diff
@@ -32,9 +33,15 @@ export const pingMiddleware = store => {
...
+      interval = setInterval(sendPing, PING_INTERVAL);
       sendPing();
     }
+    if (type === 'roundrestart') {
+      // Stop pinging because dreamseeker is currently reconnecting.
+      // Topic calls in the middle of reconnect will crash the connection.
+      clearInterval(interval);
+      return next(action);
+    }
     if (type === 'pingReply') {
```
Comment (Jared-Fogle) [inline tgui/packages/tgui-panel/ping/middleware.js:45]: wait make this an else if

**Comment by optimumtact** [comment]
you tried to trick us with your verified label but I see through your lies

**Comment by stylemistake** [comment]
It's verified with a legitimate GPG signature.

File: tgui/packages/tgui-panel/ping/middleware.js (hunk 1 above)
Comment (stylemistake) [reply tgui/packages/tgui-panel/ping/middleware.js:45]: No, because initial message should always fall through, regardless of what that message was.

**Comment by stylemistake** [comment]
@Jared-Fogle yes, `stylemistake@gmail.com`

File: tgui/packages/tgui-panel/ping/middleware.js (hunk 1 above)
Comment (Jared-Fogle) [reply tgui/packages/tgui-panel/ping/middleware.js:45]: ok

**Comment by Jared-Fogle** [comment]
image

**Comment by LemonInTheDark** [comment]
God damn it style I love you
