### PR TITLE
Fixes react version warning

### LINKED ISSUE #80432: Eslint is set to the wrong react version
## Issue Summary
We're using React 18.2 but eslint was set for 16.10 compat. Changing this will expose some errors like the use of ReactDOM.render.

## Round ID:
N/A

## Reproduction:
- Change the version in `eslintrc.yml`
- Run tgui:lint

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
image
[https://reactjs.org/link/switch-to-createroot](https://reactjs.org/link/switch-to-createroot)
## Why It's Good For The Game
Fixes #80432
## Changelog
N/A

### CODE REVIEW

File: tgui/packages/tgui/components/Tooltip.tsx [hunk 1]
```diff
@@ -1,3 +1,5 @@
+/* eslint-disable react/no-deprecated */
+// TODO: Rewrite as an FC, remove this lint disable - JLS 01/11/2023
```
Comment (Mothblocks) [inline tgui/packages/tgui/components/Tooltip.tsx:2]:
```suggestion
// TODO: Rewrite as an FC, remove this lint disable
```

This doesn't really help

**Review by Mothblocks — APPROVED** [review]
