### PR TITLE
Fixes borg logs missing from Robotact

### LINKED ISSUE #56494: RoboTact Logs are blank
Reporting client version: 513.1533

## Round ID:
[155220](https://scrubby.melonmesa.com/round/155220)

## Testmerges:
- [Dynamic 2021](https://www.github.com/tgstation/tgstation/pull/56221)

## Reproduction:
Be a cyborg or AI in a shell. Notice your logs are always empty.

### PR DESCRIPTION
**Pull request by zxaber**
## About The Pull Request
Apparently using `<NtosWindow.Content scrollable>` inside a section doesn't work anymore. This PR removes these tags from RoboTact and changes the `<Section>` tag to handle the scrolling instead, with the `<Flex.Item>` tag now handling the size of the area, allowing RoboTact to display logs once again.

Closes #56494

## Why It's Good For The Game
Fix.

## Changelog
:cl:
fix: RoboTact will now show borgs their logs again.
/:cl:

### CODE REVIEW

**Review by stylemistake — APPROVED** [review]

File: tgui/packages/tgui/interfaces/NtosRobotact.js [hunk 1]
```diff
@@ -290,18 +290,18 @@ export const NtosRobotactContent = (props, context) => {
...
-                  mb={1}
-                  key={log}>
-                  <font color="green">{log}</font>
-                </Box>
-              ))}
+            {borgLog.map(log => (
+              <Box
+                mb={1}
+                key={log}>
+                <font color="green">{log}</font>
```
Comment (stylemistake) [inline tgui/packages/tgui/interfaces/NtosRobotact.js:302]: Oh my god, how did i miss this....
