### PR TITLE
Fixes radar issues

### LINKED ISSUE #79815: Plethora of issues in `tgui-sonar` analysis
## Reproduction:

Just go into the `/bin` file from the root of your repository and run `tgui-sonar.cmd`. You'll get a shitload of issues with excellent ones such as these:

image

image

sigh... there's a bunch so if you're bored and competent at fixing js/tsx issues then you can easily crack a few of these out

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Went through tgui:sonar to search for bugs. Some of these are valid - they've been addressed. Others, not so. Telling me I need to make icon names and css classes into constants is a nit at best. Radar seems to be bugged in certain areas: Classnames ok to dupe, but not ones with conditionals. Most of the function duplication errors rely on hooks.

I think this should close #79815 and we should remove radar shortly after. See my comment [here](https://github.com/tgstation/tgstation/issues/79815#issuecomment-1859286784)
## Why It's Good For The Game
Fixes #79815
## Changelog
N/A none of this was player facing

### CODE REVIEW

File: tgui/packages/tgui/store.ts [hunk 1]
```diff
@@ -56,12 +56,10 @@ export const configureStore = (options: ConfigureStoreOptions = {}): Store => {
         ...(middleware?.post || []),
       ];
 
-  if (process.env.NODE_ENV !== 'production') {
+  if (process.env.NODE_ENV !== 'production' && sideEffects) {
     // We are using two if statements because Webpack is capable of
     // removing this specific block as dead code.
```
Comment (san7890) [inline tgui/packages/tgui/store.ts:61]: this comment is no longer relevant if you're making it one if statement now

**Review by san7890 — CHANGES_REQUESTED** [review]

File: tgui/packages/tgui/store.ts (hunk 1 above)
Comment (stylemistake) [reply tgui/packages/tgui/store.ts:61]: This comment is actually about why you should not join these if statements. It's a webpack quirk. @jlsnow301

File: tgui/packages/tgui/backend.ts [hunk 2]
```diff
@@ -51,7 +58,7 @@ const initialState = {
 export const backendReducer = (state = initialState, action) => {
   const { type, payload } = action;
 
-  if (type === 'backend/update') {
+  if (type === Action.Update) {
```
Comment (stylemistake) [inline tgui/packages/tgui/backend.ts:61]: There is no need for constant enums, because actions themselves are constants and contain types, e.g.

```
type === backendUpdate.type
```

File: tgui/packages/tgui/components/Chart.tsx [hunk 3]
```diff
@@ -50,13 +50,11 @@ const normalizeData = (
     max[1] = rangeY[1];
   }
 
-  const normalized = map((point: Point) => {
```
Comment (stylemistake) [inline tgui/packages/tgui/components/Chart.tsx:53]: This variable name was self-commenting, now it's hard to say what this code block does.

File: tgui/packages/tgui/routes.tsx [hunk 4]
```diff
@@ -59,12 +59,11 @@ export const getRoutedComponent = () => {
   if (config?.refreshing) {
     return RefreshingWindow;
   }
-  if (process.env.NODE_ENV !== 'production') {
+  if (process.env.NODE_ENV !== 'production' && debug?.kitchenSink) {
```
Comment (stylemistake) [inline tgui/packages/tgui/routes.tsx:62]: same as above because webpack

File: tgui/packages/tgui/components/Chart.tsx (hunk 3 above)
Comment (jlsnow301) [reply tgui/packages/tgui/components/Chart.tsx:53]: the function is normalizeData :P I would hope that it's normalizing it

**Review by stylemistake — APPROVED** [review]
