### PR TITLE
PDA messenger & message monitor show actual emoji, other fixes

### LINKED ISSUE #77856: Emojis don't work in PDA Messenger app
When you send a message via PDA, you can see it in the usual chat log, e.g. a checkmark. But the messenger app just shows e.g. :yes:

## Reproduction:

Send an emoji via PDA messenger

### PR DESCRIPTION
**Pull request by FlufflesTheDog**
## About The Pull Request
Makes pda messages actually appear in the messenger UI, as was supposed to be the case way back in #75820
Does the same for tcomm's message server monitor, making sure anyone trying to view pda messages is actually able to get a cohesive idea of what the message actually contained.
Also a couple of other small fixes, listed in the changelogs
image
image

Fixes #77856
## Why It's Good For The Game
Consistency, fix bugs
## Changelog
:cl: Fluffles
fix: emoji show up in the messenger UI
fix: emoji show up in the message server monitor UI
fix: you can adjust your pda ringtone in-game
fix: having an empty pAI in your pda doesn't break ringtones
fix: pdas specifically set to not consume power don't constantly switch to messenger
fix: you can use the quick-reply button for messages while resting
fix: deadchat pda messages show the imprinted sender's name instead of whoever is holding the pda
fix: emoji show up in deadchat pda messages
/:cl:

### CODE REVIEW

**Comment by Wayland-Smithy** [comment]
Does this happed to fix it for observers too?

**Comment by FlufflesTheDog** [comment]
> Does this happen to fix it for observers too, the emoji part not just the sender name?

I think emoji already appear properly in dchat pda messages

**Comment by Wayland-Smithy** [comment]
I'm pretty sure they do not:

image

**Comment by FlufflesTheDog** [comment]
Didn't even realize...
Yes, this does also fix that. Added to the changelog
image

**Comment by FlufflesTheDog** [comment]
this is ready, give me my emoji 🚀 💯 🍔 🐶 ™️

File: tgui/packages/tgui/interfaces/MessageMonitor.tsx [hunk 1]
```diff
@@ -133,7 +133,12 @@ const MessageLogsScreen = (props) => {
                 </Table.Cell>
                 <Table.Cell>{message.sender}</Table.Cell>
                 <Table.Cell>{message.recipient}</Table.Cell>
-                <Table.Cell>{message.message}</Table.Cell>
+                <Table.Cell>
+                  <Box
+                    as="span"
+                    dangerouslySetInnerHTML={{ __html: message.message }}
```
Comment (san7890) [inline tgui/packages/tgui/interfaces/MessageMonitor.tsx:139]: what safeguards do we have against users leveraging this to input their own scripts inside tgui windows? just want to make sure we've thought of this in advance

Comment (FlufflesTheDog) [reply tgui/packages/tgui/interfaces/MessageMonitor.tsx:139]: Absolutely. The emoji_parse call has been moved to the bottom of the sanitize message proc. This is called whenever any message from a pda is sent.
https://github.com/tgstation/tgstation/blob/da6b9b6e8e5416a8486bf43d350bd1626fd4c4ce/code/modules/modular_computers/file_system/programs/messenger/messenger_program.dm#L461-L471

As for non-messenger sources, any instances that might allow through unsanitized input, would already be vulnerable due to their direct output to tgchat (where emoji already show up)

I went through every source of PDA messages I could find to try and see how they handled sanitization

- Messenger app: sanitize_pda_message, sanitized
- mod pc circuits: goes through the app's send_signal function
- security officer joining: predefined message
- message monitor: tgui_input_text(), sanitized
- Request console (which uses the messaging server I guess?) html_encode, sanitized
- HUD glasses citations, tgui_input_text, sanitized
- warrant console citations: [uh oh](https://github.com/tgstation/tgstation/pull/84091)
- admin pda messages: not sanitized, presumably intentional
