### PR TITLE
Converts button to typescript

### LINKED ISSUE #78220: tgui ellipsis prop on Button component does not work
## Round ID:
N/A, local server with a recent master

## Testmerges:
N/A

## Reproduction:
Have a tgui `Button` with `ellipsis` and long content that's cut short by a `width` attribute.
Results: no ellipsies, the text just cut as the `Button` ends as if the `ellipsis` prop wasn't there
Expected: an ellipsis

Exemple:
image

Additional info:
Looking it up with F12, if the `overflow: hidden` and `text-overflow: ellipsis` props were on the `.Button__content` children, instead of the `.Button` parent they're currently on, that would make it work
image

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Converts one of our most used components into TypeScript. Fixes an issue with it where ellipses were not working. 

This is tricky though. Some people are using ellipsis prop but passing in full nodes. Tgui is not smart enough to handle this - it only works on strings! You will need to custom write the style if you're trying this. I've wrote up documentation in the component and a restrictive type that will warn anyone trying to concatenate a node.
## Why It's Good For The Game
Closes #78220
## Changelog
N/A nothing player facing

### CODE REVIEW

File: tgui/packages/tgui/interfaces/common/GasmixParser.tsx [hunk 1]
```diff
@@ -104,7 +104,7 @@ export const GasmixParser = (props: GasmixParserProps) => {
               reactionOnClick ? (
                 <Button
                   content={reaction[1]}
-                  onClick={reactionOnClick(reaction[0])}
+                  onClick={() => reactionOnClick(reaction[0])}
```
Comment (jlsnow301) [inline tgui/packages/tgui/interfaces/common/GasmixParser.tsx:107]: not sure if there is a bug report for this but this could have been very bad
