### PR TITLE
Take Two: The word filter now verbosely describes config failure (Rust-g 1.0.2 Edition)

### LINKED ISSUE #67446: Configuring the word filter TOML incorrectly does not tell you what's wrong
If there is any error in the word filter TOML, you will get this message:

image

This error gives you zero intel on what the failure *is*. In this case, it was as simple as:

image

I take the Rust philosophy where if an error message is confusing to you, it is the fault of the program and not solely your own.

This is a very easy fix--the rust-g TOML parser should provide what is essentially a Result<T, E> to DM that provides an error. We can then catch that and report it to the user.

### PR DESCRIPTION
**Pull request by san7890**
## About The Pull Request

A resuscitation of [#67474](https://github.com/tgstation/tgstation/issues/67474) since Arm is not presently able to do it.

rustg_read_toml_file has backwards dependency to support older cases that checked for lack of list (the old sign the rust fn went wrong).

Fixes [#67446](https://github.com/tgstation/tgstation/issues/67446)

The configuration for the word filter now verbosely describes the error from the bad toml to the logs, allowing problems with it to be identified quicker and resolved.

## Why It's Good For The Game

BLAZING

<details>
  <summary>Ferris warning</summary>
  
  image

</details>

## Changelog

:cl: Armhulen/Armhulenn/Bazelart/Tralezab, san7890
admin: Word filters incorrectly set up will now have their errors actually described. Please, tell your server ops when you see it so they may fix the configuration.
server: Rust-g on this codebase is now on the 1.0.2 version, prepare accordingly.
/:cl:

I also bump rust-g's DLL to 1.0.2 in this PR as well.

### CODE REVIEW

**Comment by Mothblocks** [comment]
The error we're getting is directly from the png crate. CC @ZeWaka -- "can't write indexed image without palette". Could this have been caused by one of the crate updates?

**Comment by Mothblocks** [comment]
Code in question: https://github.com/tgstation/rust-g/blob/f82e57b431a6f5106eb9eebf2e8a8a14eef07fc3/src/dmi.rs#L28-L31

**Comment by ZeWaka** [comment]
> The error we're getting in CI is directly from the png crate. CC @ZeWaka -- "can't write indexed image without palette". Could this have been caused by one of the crate updates? We updated png crate from 0.16 to 0.17.

That's annoying, I'll look at it, but I don't remember seeing anything like that in the changelogs. We also updated the `image` crate which had changes i had to modify.

**Comment by Mothblocks** [comment]
Blocked on releasing rust-g 1.0.1

**Comment by ZeWaka** [comment]
https://github.com/tgstation/rust-g/releases/tag/1.0.1

File: dependencies.sh [hunk 1]
```diff
@@ -8,7 +8,7 @@ export BYOND_MAJOR=514
 export BYOND_MINOR=1560
 
 #rust_g git tag
-export RUST_G_VERSION=0.5.0
+export RUST_G_VERSION=1.0.0
```
Comment (ZeWaka) [inline dependencies.sh:11]:
```suggestion
export RUST_G_VERSION=1.0.1
```

**Comment by san7890** [comment]
Unblocking this PR since we have 1.0.1 out now.

**Comment by san7890** [comment]
DNM until 1.0.2 comes out because this shit broken lol

**Comment by san7890** [comment]
I'm also beginning to wonder if the TramStation runtimes aren't erroneous, I haven't seen something like this on production and I know we use TOMLs to configure these... I'm going to draft this until I can see what's up with that.

**Comment by san7890** [comment]
If Tramstation passes checks, we should:tm: be:tm: good:tm.
