### PR TITLE
Fix annoying bug where window isn't refocusing after closing TGUI

### LINKED ISSUE #84446: Closing TGUI seems to randomly not refocus the game
## Issue Summary

After closing a UI the game will randomly fail to refocus. Using git bisect, seems to be caused by https://github.com/tgstation/tgstation/pull/82569 . Idk how to fix.

## Reproduction:
Start a round and open a TUI such as your PDA and close it and game will not regain focus.

### PR DESCRIPTION
**Pull request by thegrb93**
## About The Pull Request
Fix annoying bug where window isn't refocusing after closing TGUI caused by https://github.com/tgstation/tgstation/pull/82569/files#diff-4803ac36597c090dd92f3be66038bc14f9bcdf9c0b8c9422001636acfc38b333R52-R53

Fixes: #84446
## Why It's Good For The Game
Fixes annoying bug
## Changelog
:cl:
fix: Game not refocusing after closing a TGUI
/:cl:

### CODE REVIEW

File: tgui/packages/tgui/layouts/Window.tsx [hunk 1]
```diff
@@ -52,32 +52,34 @@ export const Window = (props: Props) => {
   const { config, suspended } = useBackend();
   const { debugLayout = false } = useDebug();
 
-  useEffect(() => {
-    const updateGeometry = () => {
-      const options = {
-        ...config.window,
-        size: DEFAULT_SIZE,
+  if (!suspended) {
+    useEffect(() => {
```
Comment (jlsnow301) [inline tgui/packages/tgui/layouts/Window.tsx:56]: Violates the rule of hooks, hooks cannot be conditional. Could swap this order

https://react.dev/reference/rules/rules-of-hooks

**Review by jlsnow301 — CHANGES_REQUESTED** [review]

File: tgui/packages/tgui/layouts/Window.tsx (hunk 1 above)
Comment (thegrb93) [reply tgui/packages/tgui/layouts/Window.tsx]: This better? Seems to also work.
