### PR TITLE
Fixes some character prefs issues

### LINKED ISSUE #80689: Randomization button is wonky in character prefs
## Issue Summary
Due to #80556 the randomization button in character preferences does... things whenever you select something other than none.
This is probably due to the default width of dropdowns, ie, this might be fixable by just setting `menuWidth` to something smaller

## Round ID:
Any

## Testmerges:
Any

## Reproduction:
1. open character preferences
2. click dice button on random body
3. notice the dropdowns everywhere

### LINKED ISSUE #80719: Dropdown quirk preferences are unselectable
## Issue Summary

When you press the gear it opens a menu where it shows a dropdown, and by opening that dropdown you can select your quirk preferences. Attempting to click anywhere on this opened dropdown, however, closes the first menu containing it and thus closes the dropdown and does not let you select anything.

## Reproduction:

We press the customize button on a quirk with a list of preferences.
This opens a small menu with a dropdown menu, we will call this the "customization menu".
This customization menu contains a dropdown, we will call this dropdown the "customization dropdown".

We can press anywhere within the customization menu, including opening the customization dropdown, and nothing happens.
We can press anywhere outside of the customization menu, and this closes it.
However, when we press the customization dropdown to open it, and then press anywhere on the opened customization dropdown that falls outside of the customization menu's area, it closes the customization menu, thus is closes the customization dropdown, and thus does not let you select a preference or use the scrollbar.

This seems to be caused by a recent dropper change: #80556 
image
With the code in question being:
image
Which seems to make it attempt to close the customization menu whenever one clicks outside of it. This seems to be confirmed by how removing the following snippet lets us use the customization dropdown again:
```dm
onClickOutside={() => {
    setCustomizationExpanded(false);
}}
```
However, this again makes it so the customization menu does not close when clicking outside of it, so it's not a proper fix.

But it's 6am and I'm in way over my head! _Especially_ given I don't know much about wrangling tgui.
So putting all the info I have in here for posterity.

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Issue with #80719 was resolved by using `TrackOutsideClicks` component rather than the new `onOutsideClick` prop on `Popper`. I think it was getting confused due to the fact it's nested - first the popup, then the dropdown. The dropdown selection is working.

Issue #80689 was resolved by fixing the props on `Dropdown` & `RandomizationButton`. Width and color specifically.

Now for why I'm asking for GBP for this...
#79251 added features to quirks which allowed for dropdown customization. It's a cool concept, but its implementation is very complex. I extracted components out of this into a simpler format which I think is wholly better than calling useState within .map. Even with some props drilling now in its place - I think it's a better alternative.
## Why It's Good For The Game
Bug fixes
Fixes #80719
Fixes #80689
## Changelog
:cl:
fix: Randomization button in prefs should look normal again.
fix: Quirk customization shouldn't close immediately.
/:cl:

### CODE REVIEW

File: tgui/packages/tgui/interfaces/PreferencesMenu/QuirksPage.tsx [hunk 1]
```diff
@@ -30,202 +39,256 @@ const getCorrespondingPreferences = (
...
+    serverData,
+    randomBodyEnabled,
+  } = props;
 
   return (
     // Stack is not used here for a variety of IE flex bugs
     <Box className="PreferencesMenu__Quirks__QuirkList">
-      {props.quirks.map(([quirkKey, quirk]) => {
-        const [customizationExpanded, setCustomizationExpanded] =
-          useLocalState<boolean>(quirk.name + ' customization', false);
```
Comment (jlsnow301) [inline tgui/packages/tgui/interfaces/PreferencesMenu/QuirksPage.tsx:54]: this is the big offender here, I can't let this stand

File: tgui/packages/tgui/interfaces/PreferencesMenu/QuirksPage.tsx [hunk 2]
```diff
@@ -30,202 +39,256 @@ const getCorrespondingPreferences = (
...
+    customization_options &&
+    Object.entries(customization_options).length > 0;
+
+  return (
+    <Popper
+      placement="bottom-end"
+      isOpen={customizationExpanded}
+      popperContent={
+        <TrackOutsideClicks
+          onOutsideClick={() => setCustomizationExpanded(false)}
```
Comment (jlsnow301) [inline tgui/packages/tgui/interfaces/PreferencesMenu/QuirksPage.tsx:227]: this is the fix for dropdown disappearing

**Comment by nikothedude** [comment]
bless you for improving my vestigal tsx (i am bad at tsx)
