### PR TITLE
Plumbing reaction chamber UI is scrollable again

### LINKED ISSUE #91734: Plumbing reaction chambers have no option to scroll their contents
### Client Version:

516.1662

### Issue Summary:

Neither the "Settings" or the "Catalyst" tab in a plumbing reaction chamber allow you to scroll its contents. This means if you plan to add more then 5 reagents in either tab, you must plan out the order externally and hope you didn't misinput anything. Or awkwardly shuffle around the reagents to and from the Catalyst tab. I'm pretty sure it had scrolling at one point but an update may have broken it, I can't say for sure.

### Round ID:

_No response_

### Test Merge Information:

_No response_

### Reproduction Steps:

1. Acquire a plumbing constructor.
2. Build a reaction chamber.
3. Attempt to add more then 5 reagents in the settings or the catalyst tab.
4. Cry. (Optional)

Image

### PR DESCRIPTION
**Pull request by SyncIt21**
## About The Pull Request
- Fixes #91734

## Changelog
:cl:
fix: plumbing reaction chamber UI is scrollable again
/:cl:

### CODE REVIEW

File: tgui/packages/tgui/interfaces/ChemReactionChamber.tsx [hunk 1]
```diff
@@ -134,7 +134,7 @@ export const ChemReactionChamber = (props) => {
               title="Settings"
               height="220px"
               maxHeight="220px"
-              overflow="hidden"
+              overflow="scroll"
```
Comment (jlsnow301) [inline tgui/packages/tgui/interfaces/ChemReactionChamber.tsx]: there's a prop on section just for this. use `scrollable` please

File: tgui/packages/tgui/interfaces/ChemReactionChamber.tsx [hunk 2]
```diff
@@ -270,7 +270,7 @@ export const ChemReactionChamber = (props) => {
               title="Catalysts"
               height="150px"
               maxHeight="150px"
-              overflow="hidden"
+              overflow="scroll"
```
Comment (jlsnow301) [inline tgui/packages/tgui/interfaces/ChemReactionChamber.tsx]: same

File: tgui/packages/tgui/interfaces/ChemReactionChamber.tsx (hunk 1 above)
Comment (SyncIt21) [reply tgui/packages/tgui/interfaces/ChemReactionChamber.tsx]: I tried using that yesterday and it didn't work.
I'll try it again though, maybe I'm tripping

Comment (SyncIt21) [reply tgui/packages/tgui/interfaces/ChemReactionChamber.tsx]: Nope it doesn't work.


https://github.com/user-attachments/assets/34cb234e-48ea-4777-80a2-f7c69a1f69e9

Comment (jlsnow301) [reply tgui/packages/tgui/interfaces/ChemReactionChamber.tsx]: try replacing the height props with `fill`

Comment (SyncIt21) [reply tgui/packages/tgui/interfaces/ChemReactionChamber.tsx]: But how would the section know when to display the scroll bar if we are just goanna keep expanding it's height?

The height prop tells the section if it's contents exceed that value start scrolling, but fill is just goanna keep increasing that value

None the less I'll give it a try

Comment (SyncIt21) [reply tgui/packages/tgui/interfaces/ChemReactionChamber.tsx]: I was wrong. The max height needed to be replaced with fill not the height prop itself. Thanks :)

Comment (jlsnow301) [reply tgui/packages/tgui/interfaces/ChemReactionChamber.tsx]: did that change how the ui looks at all? you can use `grow={2}`, `grow={3}` etc to get a proportional ui without having to resort to pixel measurements

Comment (SyncIt21) [reply tgui/packages/tgui/interfaces/ChemReactionChamber.tsx]: The UI looks the same because it still has its height property set. Only the maxHeight property was replaced with fill.

I'll try and use grow to see if it can be achieved

Comment (SyncIt21) [reply tgui/packages/tgui/interfaces/ChemReactionChamber.tsx]: You are awesome. `grow` is underrated Thank you for teaching me something new today :)

UI has been adjusted to display 5 reagents & 5 catalysts before scroll bar appears
