### PR TITLE
Fixes two atmos UI's [NO GBP]

### LINKED ISSUE #74748: The HFR UI is still broken, but now for a different reason.
Reporting client version: 514.1589

## Round ID:
[203802](https://scrubby.melonmesa.com/round/203802)

## Testmerges:
- [Adds a Material Stack manipulation apparatus for Engineer Cyborgs, replaces the R-Glass tool](https://www.github.com/tgstation/tgstation/pull/74297)

## Reproduction: Build the HFR. You will immediately see the injection control states the very code-looking "_ fuel__injection__rate mol/s" instead of the old default 50 mol/s, and the same for the moderator injection. In addition, these values cannot be modified to actually allow for fuel injection, or moderator injection, and will always return this text upon trying to input a value for the rates.

1. Build the HFR
2. Select a recipe
3. Try to input a value for how much fuel you wish to inject into the hfr

See also: https://github.com/tgstation/tgstation/pull/74664 and https://github.com/tgstation/tgstation/issues/74677

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
I really don't want to talk about it... fixes #74748

Bunch of old atmos UIs doing weird things that were unclear at the time of refactoring
Crystallizer was looking up labels and colors by gas name vs id
Screenshot 2023-04-15 164439
HFR, I'm still not happy with this, but this is the original implementation
```
icon={data[input_switch] ? 'power-off' : 'times'}
content={data[input_switch] ? 'On' : 'Off'}
selected={data[input_switch]}
```

## Why It's Good For The Game
Bug fixes
## Changelog
:cl:
fix: HFR should now allow you to select input/moderator rates
fix: Crystallizer ui should now properly show input gases
/:cl:

### CODE REVIEW

File: tgui/packages/tgui/interfaces/Hypertorus/Gases.tsx [hunk 1]
```diff
@@ -103,14 +103,14 @@ const GasList = (props: GasListProps, context) => {
...
-          selected={input_switch}
+          icon={data[input_switch] ? 'power-off' : 'times'}
+          content={data[input_switch] ? 'On' : 'Off'}
+          selected={data[input_switch]}
           onClick={() => act(input_switch)}
         />
         <NumberInput
           animated
-          value={input_rate}
+          value={parseFloat(data[input_rate])}
```
Comment (jlsnow301) [inline tgui/packages/tgui/interfaces/Hypertorus/Gases.tsx:113]: we probably don't even need this parsefloat here but this was the original implementation

**Comment by SyncIt21** [comment]
Please merge ASAP. HFR is still no fun without this :(
