### PR TITLE
Fixes duplicating space beer

### LINKED ISSUE #25760: Boozeomat's doing the list duplication thing
Reporting client version: 515.1621

## Issue Summary

Basically #25746 because there's two "Space Beer" things
would also be nice if #25747 could be extended to "all vendors and things that do that sort of list"

Possibly an Upstream issue?

image

## Round ID:
10185

## Testmerges:
- [Antagonist Opt In](https://github.com/Skyrat-SS13/Skyrat-tg/pull/24381)

## Reproduction:
Booze-o-mat
Pick the alcohol tab
Pick a different tab
See that Beer's also on that list
swap back and forth between alcohol and the other ones, keep adding another Space Beer entry

### LINKED ISSUE #80271: Space beer duplicating in the vending machine
Reporting client version: 514.1589

## Issue Summary

In the Booze-O-Mat, if you switch from the Alcoholic to the Non-Alcoholic tab, the "space beer" entry will duplicate itself, as many times as you enter the non-alcoholic tab.

## Round ID:
[220345](https://scrubby.melonmesa.com/round/220345)

## Testmerges:
- [Reworks SDQL2 Code to not be as reliant on `usr`](https://www.github.com/tgstation/tgstation/pull/80222)

## Reproduction:

1. Use a Booze-O-Mat.
2. Go to the non-alcoholic tab.
3. Go back to the alcoholic tab.
4. Repeat 2 and 3 until the entire page is full of space beer.

### PR DESCRIPTION
**Pull request by vinylspiders**
## About The Pull Request

Fixes https://github.com/Skyrat-SS13/Skyrat-tg/issues/25760
Fixes https://github.com/tgstation/tgstation/issues/80271

I don't know if it was a result of the react port or not (likely it was), but unexpected behavior occurs when multiple objects are mapped to the same key.

In this case, there were two items named 'Space Beer', so in order to have unique keys I've changed it so that they're keyed to the path instead of the name.

Shown below, the two types of beer:

b2SS6BiIf4

<details><summary>Beer duplicating when switching tabs</summary>

Kvm7Y0cEM8
</details>

<details><summary>No more of that</summary>

8HRol9ywN9

</details>

edit: also fixes a bug where buying an item with the same name as another would decrement the stock of both items.

<details><summary>Fixed (see space beer)</summary>

Ukkrr7ekNv

</details>

## Why It's Good For The Game

Fixes a bug

## Changelog

:cl:
fix: the boozeomat ui will stop duplicating space beer bottles
refactor: refactored vending machine backend to have unique keys for their data structures. should fix bugs related to items that happen to have the same name.
/:cl:

### CODE REVIEW

File: tgui/packages/tgui/interfaces/Vending.tsx [hunk 1]
```diff
@@ -219,7 +220,7 @@ const ProductDisplay = (props: {
           })
           .map((product) => (
             <VendingRow
-              key={product.name}
+              key={product.path || product.name}
```
Comment (SyncIt21) [inline tgui/packages/tgui/interfaces/Vending.tsx:223]:
```suggestion
              key={product.name}
```
There is no need to use  name now since path is  better and guaranteed to be unique. 

Also where is path being passed from the back end? Was it always there?

Comment (SyncIt21) [reply tgui/packages/tgui/interfaces/Vending.tsx:223]: I see, I don't feel comfortable using a var that is sometimes null and sometimes isnt best get expert opinion on this.

@jlsnow301 thoughts?

Comment (jlsnow301) [reply tgui/packages/tgui/interfaces/Vending.tsx:223]: They only need to be unique, even index is fine here

Comment (SyncIt21) [reply tgui/packages/tgui/interfaces/Vending.tsx]: > I will have you know I am doing this without breakpoints,

I feel your pain, debugger stopped working after the 515 update.

Hopefully https://github.com/tgstation/tgstation/issues/80008#issuecomment-1831471550 should help you with that.

**Comment by AdipemDragon** [comment]
even though this is just marked for the space beer thing, is this technically a general fix for crosspage duping? since this happens with playing cards from the good safe fun vendor, too (and i kind of forgot about it until seeing this pr, whoops)
