### PR TITLE
Modernized TGUI panel

### LINKED ISSUE #90773: Chat isn't scrolling properly
### Client Version:

516.1660

### Issue Summary:

Chat doesn't continuously scroll to the bottom whenever someone says something. The "Scroll to bottom" button is always visible but does nothing when I click on it. I have tried the fix-chat verb, restarting the game, BYOND, and my VM in that order, nothing fixes it.

### Round ID:

_No response_

### Test Merge Information:

_No response_

### Reproduction Steps:

1. Open chat
2. Expect it to scroll
3. it doesn't

### PR DESCRIPTION
**Pull request by jlsnow301**
## About The Pull Request
Pretty huge, sorry.

TGUI Panel is made entirely independent of TGUI backend, and thus no more redux. It's all modern global state. 
Message types expected from the backend are all neatly organized in events/listeners.ts. 
Many files have been updated or converted to typescript along the way. 

TGUI panel should behave as it did before, but hopefully it'll be more reliable and more performant.
Basically pt 2 of #94436
## Why It's Good For The Game
TGUI panel gets a big upgrade. I get to rip out redux directly after this.

For code readability, I'm drawing a clear line between what is a server message and what is a client action. The event handlers themselves are then written very straight forward, in typescript.

Fixes #90773

### CODE REVIEW

File: tgui/packages/tgui-panel/events/listeners.ts [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+  'audio/playMusic': playMusic,
+  'audio/stopMusic': stopMusic,
+  'chat/message': chatMessage,
+  'ping/reply': pingReply,
+  'ping/soft': pingSoft,
+  roundrestart,
+  'telemetry/request': telemetryRequest,
+  testTelemetryCommand,
+  update: handleTelemetryData,
+} as const;
```
Comment (jlsnow301) [inline tgui/packages/tgui-panel/events/listeners.ts:25]: checkem

**Comment by MrMelbert** [comment]
On roundend it forced open a "save chat log" dialog box

**Comment by MrMelbert** [comment]
Importing settings works only partially, it doesn't import chat tabs

**Comment by MrMelbert** [comment]
Chat tabs seem largely non-functional
`Fix-chat` deletes all tabs, toggling categories doesn't hide them from chat

**Comment by MrMelbert** [comment]
If you up font size your chat settings get thrown off the window
image

File: tgui/packages/tgui-panel/chat/renderer.tsx [hunk 2]
```diff
@@ -432,19 +446,17 @@ class ChatRenderer {
 
           const reactRoot = createRoot(childNode);
 
-          // biome-ignore-start lint/security/noDangerouslySetInnerHtml: ignore
           reactRoot.render(
             <Element {...outputProps}>
+              {/** biome-ignore lint/security/noDangerouslySetInnerHtml: its fine */}
               <span dangerouslySetInnerHTML={oldHtml} />
             </Element>,
-            childNode,
```
Comment (jlsnow301) [inline tgui/packages/tgui-panel/chat/renderer.tsx:440]: infernoism

**Comment by jlsnow301** [comment]
a wee bit out of scope but going to try to fix scroll tracking here
